checked e2e_test and made them pass

diff --git a/e2e_test/expected-pipeline.yml b/e2e_test/expected-pipeline.yml
--- a/e2e_test/expected-pipeline.yml
+++ b/e2e_test/expected-pipeline.yml
@@ -287,6 +287,22 @@ jobs:
                 echo ""
               fi
 
+              copyArtifact() {
+                ARTIFACT=$1
+                ARTIFACT_OUT_PATH=$2
+                if [ -d $ARTIFACT ] ; then
+                  mkdir -p $ARTIFACT_OUT_PATH/$ARTIFACT
+                  cp -r $ARTIFACT/. $ARTIFACT_OUT_PATH/$ARTIFACT/
+                elif [ -f $ARTIFACT ] ; then
+                  ARTIFACT_DIR=$(dirname $ARTIFACT)
+                  mkdir -p $ARTIFACT_OUT_PATH/$ARTIFACT_DIR
+                  cp $ARTIFACT $ARTIFACT_OUT_PATH/$ARTIFACT_DIR
+                else
+                  echo "ERROR: Artifact '$ARTIFACT' not found. Try fly hijack to check the filesystem."
+                  exit 1
+                fi
+              }
+
               # Copying in artifacts from previous task
               cp -r ../../artifacts/. .
 
@@ -295,12 +311,16 @@ jobs:
               ./smoke-test.sh
               EXIT_STATUS=$?
               if [ $EXIT_STATUS != 0 ] ; then
+                # Artifacts to copy in case of failure
+                copyArtifact .halfpipe.io.yml ../../artifacts-out-failure
                 exit 1
               fi
             dir: git/e2e_test
           inputs:
           - name: git
           - name: artifacts
+          outputs:
+          - name: artifacts-out-failure
           caches:
           - path: ../../../halfpipe-cache
         attempts: 1
@@ -393,6 +413,12 @@ jobs:
     attempts: 2
   on_failure:
     aggregate:
+    - put: artifacts-on-failure
+      resource: artifacts-engineering-enablement-e2e-test-on-failure
+      params:
+        folder: artifacts-out-failure
+        postfix: failure
+        version_file: git/.git/ref
     - put: slack-notification
       params:
         channel: '#ee-re'
@@ -490,6 +516,9 @@ jobs:
             ./smoke-test.sh
             EXIT_STATUS=$?
             if [ $EXIT_STATUS != 0 ] ; then
+              # Artifacts to copy in case of failure
+              copyArtifact docker-compose.yml ../../artifacts-out-failure
+              copyArtifact .halfpipe.io.yml ../../artifacts-out-failure
               exit 1
             fi
 
@@ -500,6 +529,7 @@ jobs:
         - name: git
         outputs:
         - name: artifacts-out
+        - name: artifacts-out-failure
         caches:
         - path: ../../../halfpipe-cache
       attempts: 1
@@ -553,6 +583,22 @@ jobs:
               echo ""
             fi
 
+            copyArtifact() {
+              ARTIFACT=$1
+              ARTIFACT_OUT_PATH=$2
+              if [ -d $ARTIFACT ] ; then
+                mkdir -p $ARTIFACT_OUT_PATH/$ARTIFACT
+                cp -r $ARTIFACT/. $ARTIFACT_OUT_PATH/$ARTIFACT/
+              elif [ -f $ARTIFACT ] ; then
+                ARTIFACT_DIR=$(dirname $ARTIFACT)
+                mkdir -p $ARTIFACT_OUT_PATH/$ARTIFACT_DIR
+                cp $ARTIFACT $ARTIFACT_OUT_PATH/$ARTIFACT_DIR
+              else
+                echo "ERROR: Artifact '$ARTIFACT' not found. Try fly hijack to check the filesystem."
+                exit 1
+              fi
+            }
+
             # Copying in artifacts from previous task
             cp -r ../../artifacts/. .
 
@@ -561,12 +607,16 @@ jobs:
             ./smoke-test.sh
             EXIT_STATUS=$?
             if [ $EXIT_STATUS != 0 ] ; then
+              # Artifacts to copy in case of failure
+              copyArtifact .halfpipe.io.yml ../../artifacts-out-failure
               exit 1
             fi
           dir: git/e2e_test
         inputs:
         - name: git
         - name: artifacts
+        outputs:
+        - name: artifacts-out-failure
         caches:
         - path: ../../../halfpipe-cache
       attempts: 1
@@ -579,6 +629,12 @@ jobs:
     attempts: 2
   on_failure:
     aggregate:
+    - put: artifacts-on-failure
+      resource: artifacts-engineering-enablement-e2e-test-on-failure
+      params:
+        folder: artifacts-out-failure
+        postfix: failure
+        version_file: git/.git/ref
     - put: slack-notification
       params:
         channel: '#ee-re'
@@ -670,21 +726,47 @@ jobs:
             echo ""
           fi
 
+          copyArtifact() {
+            ARTIFACT=$1
+            ARTIFACT_OUT_PATH=$2
+            if [ -d $ARTIFACT ] ; then
+              mkdir -p $ARTIFACT_OUT_PATH/$ARTIFACT
+              cp -r $ARTIFACT/. $ARTIFACT_OUT_PATH/$ARTIFACT/
+            elif [ -f $ARTIFACT ] ; then
+              ARTIFACT_DIR=$(dirname $ARTIFACT)
+              mkdir -p $ARTIFACT_OUT_PATH/$ARTIFACT_DIR
+              cp $ARTIFACT $ARTIFACT_OUT_PATH/$ARTIFACT_DIR
+            else
+              echo "ERROR: Artifact '$ARTIFACT' not found. Try fly hijack to check the filesystem."
+              exit 1
+            fi
+          }
+
           export GIT_REVISION=`cat ../.git/ref`
 
           ./notify.sh
           EXIT_STATUS=$?
           if [ $EXIT_STATUS != 0 ] ; then
+            # Artifacts to copy in case of failure
+            copyArtifact .halfpipe.io.yml ../../artifacts-out-failure
             exit 1
           fi
         dir: git/e2e_test
       inputs:
       - name: git
+      outputs:
+      - name: artifacts-out-failure
       caches:
       - path: ../../../halfpipe-cache
     attempts: 1
   on_failure:
     aggregate:
+    - put: artifacts-on-failure
+      resource: artifacts-engineering-enablement-e2e-test-on-failure
+      params:
+        folder: artifacts-out-failure
+        postfix: failure
+        version_file: git/.git/ref
     - put: slack-notification
       params:
         channel: '#ee-re'
@@ -757,6 +839,7 @@ jobs:
           if [ $EXIT_STATUS != 0 ] ; then
             # Artifacts to copy in case of failure
             copyArtifact docker-compose.yml ../../artifacts-out-failure
+            copyArtifact .halfpipe.io.yml ../../artifacts-out-failure
             exit 1
           fi
         dir: git/e2e_test
diff --git a/e2e_test_versioned/expected-pipeline.yml b/e2e_test_versioned/expected-pipeline.yml
--- a/e2e_test_versioned/expected-pipeline.yml
+++ b/e2e_test_versioned/expected-pipeline.yml
@@ -322,6 +322,22 @@ jobs:
                 echo ""
               fi
 
+              copyArtifact() {
+                ARTIFACT=$1
+                ARTIFACT_OUT_PATH=$2
+                if [ -d $ARTIFACT ] ; then
+                  mkdir -p $ARTIFACT_OUT_PATH/$ARTIFACT
+                  cp -r $ARTIFACT/. $ARTIFACT_OUT_PATH/$ARTIFACT/
+                elif [ -f $ARTIFACT ] ; then
+                  ARTIFACT_DIR=$(dirname $ARTIFACT)
+                  mkdir -p $ARTIFACT_OUT_PATH/$ARTIFACT_DIR
+                  cp $ARTIFACT $ARTIFACT_OUT_PATH/$ARTIFACT_DIR
+                else
+                  echo "ERROR: Artifact '$ARTIFACT' not found. Try fly hijack to check the filesystem."
+                  exit 1
+                fi
+              }
+
               # Copying in artifacts from previous task
               cp -r ../../artifacts/. .
 
@@ -331,6 +347,8 @@ jobs:
               ./smoke-test.sh
               EXIT_STATUS=$?
               if [ $EXIT_STATUS != 0 ] ; then
+                # Artifacts to copy in case of failure
+                copyArtifact .halfpipe.io.yml ../../artifacts-out-failure
                 exit 1
               fi
             dir: git/e2e_test_versioned
@@ -338,6 +356,8 @@ jobs:
           - name: git
           - name: artifacts
           - name: version
+          outputs:
+          - name: artifacts-out-failure
           caches:
           - path: ../../../halfpipe-cache
         attempts: 1
@@ -432,6 +452,12 @@ jobs:
     attempts: 2
   on_failure:
     aggregate:
+    - put: artifacts-on-failure
+      resource: artifacts-engineering-enablement-e2e-test-on-failure
+      params:
+        folder: artifacts-out-failure
+        postfix: failure
+        version_file: git/.git/ref
     - put: slack-notification
       params:
         channel: '#ee-re'
@@ -533,6 +559,8 @@ jobs:
             ./smoke-test.sh
             EXIT_STATUS=$?
             if [ $EXIT_STATUS != 0 ] ; then
+              # Artifacts to copy in case of failure
+              copyArtifact .halfpipe.io.yml ../../artifacts-out-failure
               exit 1
             fi
 
@@ -544,6 +572,7 @@ jobs:
         - name: version
         outputs:
         - name: artifacts-out
+        - name: artifacts-out-failure
         caches:
         - path: ../../../halfpipe-cache
       attempts: 1
@@ -597,6 +626,22 @@ jobs:
               echo ""
             fi
 
+            copyArtifact() {
+              ARTIFACT=$1
+              ARTIFACT_OUT_PATH=$2
+              if [ -d $ARTIFACT ] ; then
+                mkdir -p $ARTIFACT_OUT_PATH/$ARTIFACT
+                cp -r $ARTIFACT/. $ARTIFACT_OUT_PATH/$ARTIFACT/
+              elif [ -f $ARTIFACT ] ; then
+                ARTIFACT_DIR=$(dirname $ARTIFACT)
+                mkdir -p $ARTIFACT_OUT_PATH/$ARTIFACT_DIR
+                cp $ARTIFACT $ARTIFACT_OUT_PATH/$ARTIFACT_DIR
+              else
+                echo "ERROR: Artifact '$ARTIFACT' not found. Try fly hijack to check the filesystem."
+                exit 1
+              fi
+            }
+
             # Copying in artifacts from previous task
             cp -r ../../artifacts/. .
 
@@ -606,6 +651,8 @@ jobs:
             ./smoke-test.sh
             EXIT_STATUS=$?
             if [ $EXIT_STATUS != 0 ] ; then
+              # Artifacts to copy in case of failure
+              copyArtifact .halfpipe.io.yml ../../artifacts-out-failure
               exit 1
             fi
           dir: git/e2e_test_versioned
@@ -613,6 +660,8 @@ jobs:
         - name: git
         - name: artifacts
         - name: version
+        outputs:
+        - name: artifacts-out-failure
         caches:
         - path: ../../../halfpipe-cache
       attempts: 1
@@ -625,6 +674,12 @@ jobs:
     attempts: 2
   on_failure:
     aggregate:
+    - put: artifacts-on-failure
+      resource: artifacts-engineering-enablement-e2e-test-on-failure
+      params:
+        folder: artifacts-out-failure
+        postfix: failure
+        version_file: git/.git/ref
     - put: slack-notification
       params:
         channel: '#ee-re'
@@ -724,23 +779,49 @@ jobs:
             echo ""
           fi
 
+          copyArtifact() {
+            ARTIFACT=$1
+            ARTIFACT_OUT_PATH=$2
+            if [ -d $ARTIFACT ] ; then
+              mkdir -p $ARTIFACT_OUT_PATH/$ARTIFACT
+              cp -r $ARTIFACT/. $ARTIFACT_OUT_PATH/$ARTIFACT/
+            elif [ -f $ARTIFACT ] ; then
+              ARTIFACT_DIR=$(dirname $ARTIFACT)
+              mkdir -p $ARTIFACT_OUT_PATH/$ARTIFACT_DIR
+              cp $ARTIFACT $ARTIFACT_OUT_PATH/$ARTIFACT_DIR
+            else
+              echo "ERROR: Artifact '$ARTIFACT' not found. Try fly hijack to check the filesystem."
+              exit 1
+            fi
+          }
+
           export GIT_REVISION=`cat ../.git/ref`
           export BUILD_VERSION=`cat ../../version/version`
 
           ./notify.sh
           EXIT_STATUS=$?
           if [ $EXIT_STATUS != 0 ] ; then
+            # Artifacts to copy in case of failure
+            copyArtifact .halfpipe.io.yml ../../artifacts-out-failure
             exit 1
           fi
         dir: git/e2e_test_versioned
       inputs:
       - name: git
       - name: version
+      outputs:
+      - name: artifacts-out-failure
       caches:
       - path: ../../../halfpipe-cache
     attempts: 1
   on_failure:
     aggregate:
+    - put: artifacts-on-failure
+      resource: artifacts-engineering-enablement-e2e-test-on-failure
+      params:
+        folder: artifacts-out-failure
+        postfix: failure
+        version_file: git/.git/ref
     - put: slack-notification
       params:
         channel: '#ee-re'
@@ -817,6 +898,7 @@ jobs:
           if [ $EXIT_STATUS != 0 ] ; then
             # Artifacts to copy in case of failure
             copyArtifact docker-compose.yml ../../artifacts-out-failure
+            copyArtifact .halfpipe.io.yml ../../artifacts-out-failure
             exit 1
           fi
         dir: git/e2e_test_versioned
