allow cdc task to go anywhere as long as you set provider_host

diff --git a/e2e_test/expected-pipeline.yml b/e2e_test/expected-pipeline.yml
--- a/e2e_test/expected-pipeline.yml
+++ b/e2e_test/expected-pipeline.yml
@@ -478,4 +478,89 @@ jobs:
       icon_url: https://concourse.halfpipe.io/public/images/favicon-failed.png
       text: The pipeline `$BUILD_PIPELINE_NAME` failed at `$BUILD_JOB_NAME`. <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
       username: Halfpipe
+- name: another-c-name
+  serial: true
+  plan:
+  - get: git
+    passed:
+    - docker-compose
+    trigger: true
+  - task: run
+    privileged: true
+    config:
+      platform: linux
+      image_resource:
+        type: docker-image
+        source:
+          password: ((gcr.private_key))
+          repository: eu.gcr.io/halfpipe-io/halfpipe-cdc-runner
+          tag: latest
+          username: _json_key
+      params:
+        CONSUMER_GIT_KEY: ((github.private_key))
+        CONSUMER_GIT_URI: git@github.com:springernature/c-consumer
+        CONSUMER_HOST: c-host
+        CONSUMER_PATH: ""
+        CONSUMER_SCRIPT: c-script
+        DOCKER_COMPOSE_SERVICE: potato
+        PROVIDER_HOST: p-host
+        PROVIDER_HOST_KEY: E2E_TEST_DEPLOYED_HOST
+        PROVIDER_NAME: e2e-test
+      run:
+        path: /bin/sh
+        args:
+        - -c
+        - |
+          which bash > /dev/null
+          if [ $? != 0 ]; then
+            echo "Bash is not present in the docker image"
+            echo "If you script, or any of the script your script is calling depends on bash you will get a strange error message like:"
+            echo "sh: yourscript.sh: command not found"
+            echo "To fix, make sure your docker image contains bash!"
+            echo ""
+            echo ""
+          fi
+          set -e
+          export GIT_REVISION=`cat .git/ref`
+          \source /docker-lib.sh
+          start_docker
+
+          # get current revision of consumer
+          REVISION=$(curl "${CONSUMER_HOST}/internal/version" | jq -r '.revision')
+
+          # write git key to file
+          echo "${CONSUMER_GIT_KEY}" > .gitkey
+          chmod 600 .gitkey
+
+          set -x
+
+          # clone consumer into "consumer-repo" dir
+          GIT_SSH_COMMAND="ssh -o StrictHostKeychecking=no -i .gitkey" git clone ${CONSUMER_GIT_URI} consumer-repo
+          cd consumer-repo/${CONSUMER_PATH}
+
+          # checkout revision
+          git checkout ${REVISION}
+
+          # run the tests in code container
+          # note: old system reads CF manifest env vars and sets them all here
+          docker-compose run --no-deps \
+            -e DEPENDENCY_NAME=${PROVIDER_NAME} \
+            -e ${PROVIDER_HOST_KEY}=${PROVIDER_HOST} \
+            ${DOCKER_COMPOSE_SERVICE:-code} \
+            /home/dev/code/${CONSUMER_SCRIPT}
+
+          rc=$?
+          docker-compose down
+          [ $rc -eq 0 ] || exit $rc
+        dir: git
+      inputs:
+      - name: git
+        path: ""
+  on_failure:
+    put: slack
+    params:
+      channel: '#ee-re'
+      icon_url: https://concourse.halfpipe.io/public/images/favicon-failed.png
+      text: The pipeline `$BUILD_PIPELINE_NAME` failed at `$BUILD_JOB_NAME`. <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
+      username: Halfpipe
 
