Print warning if docker image doesnt contain bash, since its a frequent issue for users

diff --git a/e2e_test/expected-pipeline.yml b/e2e_test/expected-pipeline.yml
--- a/e2e_test/expected-pipeline.yml
+++ b/e2e_test/expected-pipeline.yml
@@ -70,8 +70,18 @@ jobs:
       run:
         path: /bin/sh
         args:
-        - -ec
+        - -c
         - |
+          which bash > /dev/null
+          if [ $? != 0 ]; then
+            echo "Bash is not present in the docker image"
+            echo "If you script, or any of the script your script is calling depends on bash you will get a strange error message like:"
+            echo "sh: yourscript.sh: command not found"
+            echo "To fix, make sure your docker image contains bash!"
+            echo ""
+            echo ""
+          fi
+          set -e
           export GIT_REVISION=`cat .git/ref`
           ./test.sh
 
@@ -194,8 +204,18 @@ jobs:
       run:
         path: /bin/sh
         args:
-        - -ec
+        - -c
         - |-
+          which bash > /dev/null
+          if [ $? != 0 ]; then
+            echo "Bash is not present in the docker image"
+            echo "If you script, or any of the script your script is calling depends on bash you will get a strange error message like:"
+            echo "sh: yourscript.sh: command not found"
+            echo "To fix, make sure your docker image contains bash!"
+            echo ""
+            echo ""
+          fi
+          set -e
           export GIT_REVISION=`cat .git/ref`
           ./smoke-test.sh
         dir: git
@@ -273,8 +293,18 @@ jobs:
       run:
         path: /bin/sh
         args:
-        - -ec
+        - -c
         - |-
+          which bash > /dev/null
+          if [ $? != 0 ]; then
+            echo "Bash is not present in the docker image"
+            echo "If you script, or any of the script your script is calling depends on bash you will get a strange error message like:"
+            echo "sh: yourscript.sh: command not found"
+            echo "To fix, make sure your docker image contains bash!"
+            echo ""
+            echo ""
+          fi
+          set -e
           export GIT_REVISION=`cat .git/ref`
           ./notify.sh
         dir: git
@@ -309,8 +339,18 @@ jobs:
       run:
         path: /bin/sh
         args:
-        - -ec
+        - -c
         - |
+          which bash > /dev/null
+          if [ $? != 0 ]; then
+            echo "Bash is not present in the docker image"
+            echo "If you script, or any of the script your script is calling depends on bash you will get a strange error message like:"
+            echo "sh: yourscript.sh: command not found"
+            echo "To fix, make sure your docker image contains bash!"
+            echo ""
+            echo ""
+          fi
+          set -e
           export GIT_REVISION=`cat .git/ref`
           \source /docker-lib.sh
           start_docker
