wip - write failing e2e-test and add on_failure field to halfpipe manifest

diff --git a/e2e_test/expected-pipeline.yml b/e2e_test/expected-pipeline.yml
--- a/e2e_test/expected-pipeline.yml
+++ b/e2e_test/expected-pipeline.yml
@@ -125,12 +125,41 @@ jobs:
       folder: artifacts
       version_file: git/.git/ref
   on_failure:
-    put: slack
-    params:
-      channel: '#ee-re'
-      icon_url: https://concourse.halfpipe.io/public/images/favicon-failed.png
-      text: The pipeline `$BUILD_PIPELINE_NAME` failed at `$BUILD_JOB_NAME`. <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
-      username: Halfpipe
+    do:
+    - put: slack
+      params:
+        channel: '#ee-re'
+        icon_url: https://concourse.halfpipe.io/public/images/favicon-failed.png
+        text: The pipeline `$BUILD_PIPELINE_NAME` failed at `$BUILD_JOB_NAME`. <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
+        username: Halfpipe
+    - task: run on failure task
+        config:
+          platform: linux
+          image_resource:
+            type: docker-image
+            source:
+              repository: node:9.5.0-alpine
+          run:
+            path: /bin/sh
+            args:
+            - -c
+            - |-
+              which bash > /dev/null
+              if [ $? != 0 ]; then
+                echo "WARNING: Bash is not present in the docker image"
+                echo "If your script depends on bash you will get a strange error message like:"
+                echo "  sh: yourscript.sh: command not found"
+                echo "To fix, make sure your docker image contains bash!"
+                echo ""
+                echo ""
+              fi
+              set -e
+              export GIT_REVISION=`cat .git/ref`
+              ./blah.sh
+            dir: git
+          inputs:
+          - name: git
+            path: ""
 - name: deploy-cf
   serial: true
   plan:
@@ -159,12 +188,41 @@ jobs:
       manifestPath: git/manifest.yml
       testDomain: some.random.domain.com
   on_failure:
-    put: slack
-    params:
-      channel: '#ee-re'
-      icon_url: https://concourse.halfpipe.io/public/images/favicon-failed.png
-      text: The pipeline `$BUILD_PIPELINE_NAME` failed at `$BUILD_JOB_NAME`. <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
-      username: Halfpipe
+    do:
+    - put: slack
+      params:
+        channel: '#ee-re'
+        icon_url: https://concourse.halfpipe.io/public/images/favicon-failed.png
+        text: The pipeline `$BUILD_PIPELINE_NAME` failed at `$BUILD_JOB_NAME`. <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
+        username: Halfpipe
+    - task: run on failure task
+        config:
+          platform: linux
+          image_resource:
+            type: docker-image
+            source:
+              repository: node:9.5.0-alpine
+          run:
+            path: /bin/sh
+            args:
+            - -c
+            - |-
+              which bash > /dev/null
+              if [ $? != 0 ]; then
+                echo "WARNING: Bash is not present in the docker image"
+                echo "If your script depends on bash you will get a strange error message like:"
+                echo "  sh: yourscript.sh: command not found"
+                echo "To fix, make sure your docker image contains bash!"
+                echo ""
+                echo ""
+              fi
+              set -e
+              export GIT_REVISION=`cat .git/ref`
+              ./blah.sh
+            dir: git
+          inputs:
+          - name: git
+            path: ""
   ensure:
     put: cf halfpipe-cleanup
     resource: CF dev-api engineering-enablement dev
@@ -302,12 +360,41 @@ jobs:
         A: "0.1"
         B: "false"
   on_failure:
-    put: slack
-    params:
-      channel: '#ee-re'
-      icon_url: https://concourse.halfpipe.io/public/images/favicon-failed.png
-      text: The pipeline `$BUILD_PIPELINE_NAME` failed at `$BUILD_JOB_NAME`. <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
-      username: Halfpipe
+    do:
+    - put: slack
+      params:
+        channel: '#ee-re'
+        icon_url: https://concourse.halfpipe.io/public/images/favicon-failed.png
+        text: The pipeline `$BUILD_PIPELINE_NAME` failed at `$BUILD_JOB_NAME`. <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
+        username: Halfpipe
+    - task: run on failure task
+        config:
+          platform: linux
+          image_resource:
+            type: docker-image
+            source:
+              repository: node:9.5.0-alpine
+          run:
+            path: /bin/sh
+            args:
+            - -c
+            - |-
+              which bash > /dev/null
+              if [ $? != 0 ]; then
+                echo "WARNING: Bash is not present in the docker image"
+                echo "If your script depends on bash you will get a strange error message like:"
+                echo "  sh: yourscript.sh: command not found"
+                echo "To fix, make sure your docker image contains bash!"
+                echo ""
+                echo ""
+              fi
+              set -e
+              export GIT_REVISION=`cat .git/ref`
+              ./blah.sh
+            dir: git
+          inputs:
+          - name: git
+            path: ""
   ensure:
     put: cf halfpipe-cleanup
     resource: CF api-live pe staging
@@ -334,12 +421,41 @@ jobs:
         A: a
         B: b
   on_failure:
-    put: slack
-    params:
-      channel: '#ee-re'
-      icon_url: https://concourse.halfpipe.io/public/images/favicon-failed.png
-      text: The pipeline `$BUILD_PIPELINE_NAME` failed at `$BUILD_JOB_NAME`. <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
-      username: Halfpipe
+    do:
+    - put: slack
+      params:
+        channel: '#ee-re'
+        icon_url: https://concourse.halfpipe.io/public/images/favicon-failed.png
+        text: The pipeline `$BUILD_PIPELINE_NAME` failed at `$BUILD_JOB_NAME`. <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
+        username: Halfpipe
+    - task: run on failure task
+        config:
+          platform: linux
+          image_resource:
+            type: docker-image
+            source:
+              repository: node:9.5.0-alpine
+          run:
+            path: /bin/sh
+            args:
+            - -c
+            - |-
+              which bash > /dev/null
+              if [ $? != 0 ]; then
+                echo "WARNING: Bash is not present in the docker image"
+                echo "If your script depends on bash you will get a strange error message like:"
+                echo "  sh: yourscript.sh: command not found"
+                echo "To fix, make sure your docker image contains bash!"
+                echo ""
+                echo ""
+              fi
+              set -e
+              export GIT_REVISION=`cat .git/ref`
+              ./blah.sh
+            dir: git
+          inputs:
+          - name: git
+            path: ""
 - name: run notify.sh
   serial: true
   plan:
@@ -382,12 +498,41 @@ jobs:
       - name: git
         path: ""
   on_failure:
-    put: slack
-    params:
-      channel: '#ee-re'
-      icon_url: https://concourse.halfpipe.io/public/images/favicon-failed.png
-      text: The pipeline `$BUILD_PIPELINE_NAME` failed at `$BUILD_JOB_NAME`. <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
-      username: Halfpipe
+   do:
+   - put: slack
+     params:
+       channel: '#ee-re'
+       icon_url: https://concourse.halfpipe.io/public/images/favicon-failed.png
+       text: The pipeline `$BUILD_PIPELINE_NAME` failed at `$BUILD_JOB_NAME`. <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
+       username: Halfpipe
+   - task: run on failure task
+       config:
+         platform: linux
+         image_resource:
+           type: docker-image
+           source:
+             repository: node:9.5.0-alpine
+         run:
+           path: /bin/sh
+           args:
+           - -c
+           - |-
+             which bash > /dev/null
+             if [ $? != 0 ]; then
+               echo "WARNING: Bash is not present in the docker image"
+               echo "If your script depends on bash you will get a strange error message like:"
+               echo "  sh: yourscript.sh: command not found"
+               echo "To fix, make sure your docker image contains bash!"
+               echo ""
+               echo ""
+             fi
+             set -e
+             export GIT_REVISION=`cat .git/ref`
+             ./blah.sh
+           dir: git
+         inputs:
+         - name: git
+           path: ""
 - name: docker-compose
   serial: true
   plan:
@@ -428,12 +573,41 @@ jobs:
       - name: git
         path: ""
   on_failure:
-    put: slack
-    params:
-      channel: '#ee-re'
-      icon_url: https://concourse.halfpipe.io/public/images/favicon-failed.png
-      text: The pipeline `$BUILD_PIPELINE_NAME` failed at `$BUILD_JOB_NAME`. <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
-      username: Halfpipe
+    do:
+    - put: slack
+      params:
+        channel: '#ee-re'
+        icon_url: https://concourse.halfpipe.io/public/images/favicon-failed.png
+        text: The pipeline `$BUILD_PIPELINE_NAME` failed at `$BUILD_JOB_NAME`. <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
+        username: Halfpipe
+    - task: run on failure task
+        config:
+          platform: linux
+          image_resource:
+            type: docker-image
+            source:
+              repository: node:9.5.0-alpine
+          run:
+            path: /bin/sh
+            args:
+            - -c
+            - |-
+              which bash > /dev/null
+              if [ $? != 0 ]; then
+                echo "WARNING: Bash is not present in the docker image"
+                echo "If your script depends on bash you will get a strange error message like:"
+                echo "  sh: yourscript.sh: command not found"
+                echo "To fix, make sure your docker image contains bash!"
+                echo ""
+                echo ""
+              fi
+              set -e
+              export GIT_REVISION=`cat .git/ref`
+              ./blah.sh
+            dir: git
+          inputs:
+          - name: git
+            path: ""
 - name: another-c-name
   serial: true
   plan:
@@ -506,10 +680,39 @@ jobs:
       - name: git
         path: ""
   on_failure:
-    put: slack
-    params:
-      channel: '#ee-re'
-      icon_url: https://concourse.halfpipe.io/public/images/favicon-failed.png
-      text: The pipeline `$BUILD_PIPELINE_NAME` failed at `$BUILD_JOB_NAME`. <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
-      username: Halfpipe
+    do:
+    - put: slack
+      params:
+        channel: '#ee-re'
+        icon_url: https://concourse.halfpipe.io/public/images/favicon-failed.png
+        text: The pipeline `$BUILD_PIPELINE_NAME` failed at `$BUILD_JOB_NAME`. <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
+        username: Halfpipe
+    - task: run on failure task
+        config:
+          platform: linux
+          image_resource:
+            type: docker-image
+            source:
+              repository: node:9.5.0-alpine
+          run:
+            path: /bin/sh
+            args:
+            - -c
+            - |-
+              which bash > /dev/null
+              if [ $? != 0 ]; then
+                echo "WARNING: Bash is not present in the docker image"
+                echo "If your script depends on bash you will get a strange error message like:"
+                echo "  sh: yourscript.sh: command not found"
+                echo "To fix, make sure your docker image contains bash!"
+                echo ""
+                echo ""
+              fi
+              set -e
+              export GIT_REVISION=`cat .git/ref`
+              ./blah.sh
+            dir: git
+          inputs:
+          - name: git
+            path: ""
 
