added functionality so that pre-promote tasks are run in parallel

diff --git a/e2e_test/expected-pipeline.yml b/e2e_test/expected-pipeline.yml
--- a/e2e_test/expected-pipeline.yml
+++ b/e2e_test/expected-pipeline.yml
@@ -31,6 +31,14 @@ resources:
     password: very-secret
     space: staging
     username: michiel
+- name: CF api-live pe staging (1)
+  type: cf-resource
+  source:
+    api: ((cloudfoundry.api-live))
+    org: pe
+    password: very-secret
+    space: staging
+    username: michiel
 - name: Docker Registry
   type: docker-image
   source:
@@ -269,108 +277,115 @@ jobs:
         A: "0.1"
         B: "false"
     attempts: 2
-  - task: run smoke-test.sh
-    config:
-      platform: linux
-      image_resource:
-        type: docker-image
-        source:
-          password: ((gcr.private_key))
-          repository: eu.gcr.io/halfpipe-io/halfpipe-fly
-          tag: latest
-          username: _json_key
-      params:
-        A: blah
-        TEST_ROUTE: halfpipe-example-kotlin-dev-staging-CANDIDATE.live.cf.private.springer.com
-      run:
-        path: /bin/sh
-        args:
-        - -c
-        - |-
-          which bash > /dev/null
-          if [ $? != 0 ]; then
-            echo "WARNING: Bash is not present in the docker image"
-            echo "If your script depends on bash you will get a strange error message like:"
-            echo "  sh: yourscript.sh: command not found"
-            echo "To fix, make sure your docker image contains bash!"
-            echo ""
-            echo ""
-          fi
-          set -e
-          export GIT_REVISION=`cat .git/ref`
-          ./smoke-test.sh
-        dir: git
-      inputs:
-      - name: git
-        path: ""
-      caches:
-      - path: ../../../root/.gradle/
-      - path: ../../../root/.m2/
-      - path: ../../../root/.ivy2/
-      - path: ../../../root/.sbt/
-  - task: c-name
-    privileged: true
-    config:
-      platform: linux
-      image_resource:
-        type: docker-image
-        source:
-          password: ((gcr.private_key))
-          repository: eu.gcr.io/halfpipe-io/halfpipe-docker-compose
-          tag: latest
-          username: _json_key
-      params:
-        CONSUMER_GIT_KEY: ((github.private_key))
-        CONSUMER_GIT_URI: git@github.com:springernature/c-consumer
-        CONSUMER_HOST: c-host
-        CONSUMER_PATH: ""
-        CONSUMER_SCRIPT: /var/c-script
-        DOCKER_COMPOSE_SERVICE: ""
-        GCR_PRIVATE_KEY: ((gcr.private_key))
-        PROVIDER_HOST: halfpipe-example-kotlin-dev-staging-CANDIDATE.live.cf.private.springer.com
-        PROVIDER_HOST_KEY: E2E_TEST_DEPLOYED_HOST
-        PROVIDER_NAME: e2e-test
-      run:
-        path: docker.sh
-        args:
-        - -c
-        - |
-          set -e
-          export GIT_REVISION=`cat .git/ref`
-          \docker login -u _json_key -p "$GCR_PRIVATE_KEY" https://eu.gcr.io
+  - aggregate:
+    - do:
+      - get: artifacts-engineering-enablement-e2e-test
+      - task: run smoke-test.sh
+        config:
+          platform: linux
+          image_resource:
+            type: docker-image
+            source:
+              password: ((gcr.private_key))
+              repository: eu.gcr.io/halfpipe-io/halfpipe-fly
+              tag: latest
+              username: _json_key
+          params:
+            A: blah
+            TEST_ROUTE: halfpipe-example-kotlin-dev-staging-CANDIDATE.live.cf.private.springer.com
+          run:
+            path: /bin/sh
+            args:
+            - -c
+            - |-
+              which bash > /dev/null
+              if [ $? != 0 ]; then
+                echo "WARNING: Bash is not present in the docker image"
+                echo "If your script depends on bash you will get a strange error message like:"
+                echo "  sh: yourscript.sh: command not found"
+                echo "To fix, make sure your docker image contains bash!"
+                echo ""
+                echo ""
+              fi
+              cp -r ../artifacts/. .
+              set -e
+              export GIT_REVISION=`cat .git/ref`
+              ./smoke-test.sh
+            dir: git
+          inputs:
+          - name: git
+            path: ""
+          - name: artifacts-engineering-enablement-e2e-test
+            path: artifacts
+          caches:
+          - path: ../../../root/.gradle/
+          - path: ../../../root/.m2/
+          - path: ../../../root/.ivy2/
+          - path: ../../../root/.sbt/
+    - do:
+      - task: c-name
+        privileged: true
+        config:
+          platform: linux
+          image_resource:
+            type: docker-image
+            source:
+              password: ((gcr.private_key))
+              repository: eu.gcr.io/halfpipe-io/halfpipe-docker-compose
+              tag: latest
+              username: _json_key
+          params:
+            CONSUMER_GIT_KEY: ((github.private_key))
+            CONSUMER_GIT_URI: git@github.com:springernature/c-consumer
+            CONSUMER_HOST: c-host
+            CONSUMER_PATH: ""
+            CONSUMER_SCRIPT: /var/c-script
+            DOCKER_COMPOSE_SERVICE: ""
+            GCR_PRIVATE_KEY: ((gcr.private_key))
+            PROVIDER_HOST: halfpipe-example-kotlin-dev-staging-CANDIDATE.live.cf.private.springer.com
+            PROVIDER_HOST_KEY: E2E_TEST_DEPLOYED_HOST
+            PROVIDER_NAME: e2e-test
+          run:
+            path: docker.sh
+            args:
+            - -c
+            - |
+              set -e
+              export GIT_REVISION=`cat .git/ref`
+              \docker login -u _json_key -p "$GCR_PRIVATE_KEY" https://eu.gcr.io
 
-          # write git key to file
-          echo "${CONSUMER_GIT_KEY}" > .gitkey
-          chmod 600 .gitkey
+              # write git key to file
+              echo "${CONSUMER_GIT_KEY}" > .gitkey
+              chmod 600 .gitkey
 
-          set -x
+              set -x
 
-          # get current revision of consumer
-          REVISION=$(curl "${CONSUMER_HOST}/internal/version" | jq -r '.revision')
+              # get current revision of consumer
+              REVISION=$(curl "${CONSUMER_HOST}/internal/version" | jq -r '.revision')
 
-          # clone consumer into "consumer-repo" dir
-          GIT_SSH_COMMAND="ssh -o StrictHostKeychecking=no -i .gitkey" git clone ${CONSUMER_GIT_URI} consumer-repo
-          cd consumer-repo/${CONSUMER_PATH}
+              # clone consumer into "consumer-repo" dir
+              GIT_SSH_COMMAND="ssh -o StrictHostKeychecking=no -i .gitkey" git clone ${CONSUMER_GIT_URI} consumer-repo
+              cd consumer-repo/${CONSUMER_PATH}
 
-          # checkout revision
-          git checkout ${REVISION}
+              # checkout revision
+              git checkout ${REVISION}
 
-          # run the tests with docker-compose
-          # note: old system reads CF manifest env vars and sets them all here
-          docker-compose run --no-deps \
-            --entrypoint "${CONSUMER_SCRIPT}" \
-            -e DEPENDENCY_NAME=${PROVIDER_NAME} \
-            -e ${PROVIDER_HOST_KEY}=${PROVIDER_HOST} \
-            ${DOCKER_COMPOSE_SERVICE:-code}
-        dir: git
-      inputs:
-      - name: git
-        path: ""
-      caches:
-      - path: ../../../root/.gradle/
-      - path: ../../../root/.m2/
-      - path: ../../../root/.ivy2/
-      - path: ../../../root/.sbt/
+              # run the tests with docker-compose
+              # note: old system reads CF manifest env vars and sets them all here
+              docker-compose run --no-deps \
+                --entrypoint "${CONSUMER_SCRIPT}" \
+                -e DEPENDENCY_NAME=${PROVIDER_NAME} \
+                -e ${PROVIDER_HOST_KEY}=${PROVIDER_HOST} \
+                ${DOCKER_COMPOSE_SERVICE:-code}
+            dir: git
+          inputs:
+          - name: git
+            path: ""
+          caches:
+          - path: ../../../root/.gradle/
+          - path: ../../../root/.m2/
+          - path: ../../../root/.ivy2/
+          - path: ../../../root/.sbt/
   - put: cf halfpipe-promote
     resource: CF api-live pe staging
     params:
@@ -423,6 +438,185 @@ jobs:
   ensure:
     put: cf halfpipe-cleanup
     resource: CF api-live pe staging
+    params:
+      command: halfpipe-cleanup
+      manifestPath: git/manifest.yml
+    attempts: 2
+- name: deploy to staging (1)
+  serial: true
+  plan:
+  - aggregate:
+    - get: git
+      passed:
+      - deploy to cf
+      trigger: true
+  - put: cf halfpipe-push
+    resource: CF api-live pe staging (1)
+    params:
+      appPath: git
+      command: halfpipe-push
+      gitRefPath: git/.git/ref
+      manifestPath: git/manifest.yml
+      testDomain: live.cf.private.springer.com
+      vars:
+        A: "0.1"
+        B: "false"
+  - do:
+    - task: save-artifact-in-pre-promote
+      config:
+        platform: linux
+        image_resource:
+          type: docker-image
+          source:
+            password: ((gcr.private_key))
+            repository: eu.gcr.io/halfpipe-io/halfpipe-fly
+            tag: latest
+            username: _json_key
+        params:
+          A: blah
+          TEST_ROUTE: halfpipe-example-kotlin-dev-staging-CANDIDATE.live.cf.private.springer.com
+        run:
+          path: /bin/sh
+          args:
+          - -c
+          - |
+            which bash > /dev/null
+            if [ $? != 0 ]; then
+              echo "WARNING: Bash is not present in the docker image"
+              echo "If your script depends on bash you will get a strange error message like:"
+              echo "  sh: yourscript.sh: command not found"
+              echo "To fix, make sure your docker image contains bash!"
+              echo ""
+              echo ""
+            fi
+            set -e
+            export GIT_REVISION=`cat .git/ref`
+            ./smoke-test.sh
+
+            if [ -d build ]
+            then
+              mkdir -p ../artifacts/build
+              cp -r build/. ../artifacts/build/
+            elif [ -f build ]
+            then
+              artifactDir=$(dirname build)
+              mkdir -p ../artifacts/$artifactDir
+              cp build ../artifacts/$artifactDir
+            else
+              echo "ERROR: Artifact 'build' not found. Try fly hijack to check the filesystem."
+              exit 1
+            fi
+          dir: git
+        inputs:
+        - name: git
+          path: ""
+        outputs:
+        - name: artifacts
+          path: ""
+        caches:
+        - path: ../../../root/.gradle/
+        - path: ../../../root/.m2/
+        - path: ../../../root/.ivy2/
+        - path: ../../../root/.sbt/
+    - put: artifacts-engineering-enablement-e2e-test
+      params:
+        folder: artifacts
+        version_file: git/.git/ref
+  - do:
+    - get: artifacts-engineering-enablement-e2e-test
+    - task: restore artifact in pre promote
+      config:
+        platform: linux
+        image_resource:
+          type: docker-image
+          source:
+            password: ((gcr.private_key))
+            repository: eu.gcr.io/halfpipe-io/halfpipe-fly
+            tag: latest
+            username: _json_key
+        params:
+          A: blah
+          TEST_ROUTE: halfpipe-example-kotlin-dev-staging-CANDIDATE.live.cf.private.springer.com
+        run:
+          path: /bin/sh
+          args:
+          - -c
+          - |-
+            which bash > /dev/null
+            if [ $? != 0 ]; then
+              echo "WARNING: Bash is not present in the docker image"
+              echo "If your script depends on bash you will get a strange error message like:"
+              echo "  sh: yourscript.sh: command not found"
+              echo "To fix, make sure your docker image contains bash!"
+              echo ""
+              echo ""
+            fi
+            cp -r ../artifacts/. .
+            set -e
+            export GIT_REVISION=`cat .git/ref`
+            ./smoke-test.sh
+          dir: git
+        inputs:
+        - name: git
+          path: ""
+        - name: artifacts-engineering-enablement-e2e-test
+          path: artifacts
+        caches:
+        - path: ../../../root/.gradle/
+        - path: ../../../root/.m2/
+        - path: ../../../root/.ivy2/
+        - path: ../../../root/.sbt/
+  - put: cf halfpipe-promote
+    resource: CF api-live pe staging (1)
+    params:
+      command: halfpipe-promote
+      manifestPath: git/manifest.yml
+      testDomain: live.cf.private.springer.com
+  on_failure:
+    do:
+    - put: slack
+      params:
+        channel: '#ee-re'
+        icon_url: https://concourse.halfpipe.io/public/images/favicon-failed.png
+        text: The pipeline `$BUILD_PIPELINE_NAME` failed at `$BUILD_JOB_NAME`. <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
+        username: Halfpipe
+    - task: run on failure task
+      config:
+        platform: linux
+        image_resource:
+          type: docker-image
+          source:
+            repository: node
+            tag: 9.5.0-alpine
+        run:
+          path: /bin/sh
+          args:
+          - -c
+          - |-
+            which bash > /dev/null
+            if [ $? != 0 ]; then
+              echo "WARNING: Bash is not present in the docker image"
+              echo "If your script depends on bash you will get a strange error message like:"
+              echo "  sh: yourscript.sh: command not found"
+              echo "To fix, make sure your docker image contains bash!"
+              echo ""
+              echo ""
+            fi
+            set -e
+            export GIT_REVISION=`cat .git/ref`
+            ./blah.sh
+          dir: git
+        inputs:
+        - name: git
+          path: ""
+        caches:
+        - path: ../../../root/.gradle/
+        - path: ../../../root/.m2/
+        - path: ../../../root/.ivy2/
+        - path: ../../../root/.sbt/
+  ensure:
+    put: cf halfpipe-cleanup
+    resource: CF api-live pe staging (1)
     params:
       command: halfpipe-cleanup
       manifestPath: git/manifest.yml
