switched from deprecated aggregate to inparallel

diff --git a/e2e/deploy-cf/expected-pipeline.yml b/e2e/deploy-cf/expected-pipeline.yml
--- a/e2e/deploy-cf/expected-pipeline.yml
+++ b/e2e/deploy-cf/expected-pipeline.yml
@@ -29,9 +29,10 @@ jobs:
 - name: deploy to cf
   serial: true
   plan:
-  - aggregate:
-    - get: git
-      trigger: true
+  - in_parallel:
+      steps:
+      - get: git
+        trigger: true
     timeout: 5m
   - put: cf halfpipe-push
     resource: CF dev-api test dev
@@ -44,64 +45,65 @@ jobs:
       timeout: 5m
     timeout: 5m
     attempts: 2
-  - aggregate:
-    - do:
-      - task: pre promote step
-        config:
-          platform: linux
-          image_resource:
-            type: registry-image
-            source:
-              password: ((halfpipe-gcr.private_key))
-              repository: eu.gcr.io/halfpipe-io/halfpipe-fly
-              tag: latest
-              username: _json_key
-          params:
-            A: blah
-            ARTIFACTORY_PASSWORD: ((artifactory.password))
-            ARTIFACTORY_URL: ((artifactory.url))
-            ARTIFACTORY_USERNAME: ((artifactory.username))
-            TEST_ROUTE: halfpipe-example-kotlin-dev-dev-CANDIDATE.some.random.domain.com
-          run:
-            path: /bin/sh
-            args:
-            - -c
-            - |
-              which bash > /dev/null
-              if [ $? != 0 ]; then
-                echo "WARNING: Bash is not present in the docker image"
-                echo "If your script depends on bash you will get a strange error message like:"
-                echo "  sh: yourscript.sh: command not found"
-                echo "To fix, make sure your docker image contains bash!"
-                echo ""
-                echo ""
-              fi
+  - in_parallel:
+      steps:
+      - do:
+        - task: pre promote step
+          config:
+            platform: linux
+            image_resource:
+              type: registry-image
+              source:
+                password: ((halfpipe-gcr.private_key))
+                repository: eu.gcr.io/halfpipe-io/halfpipe-fly
+                tag: latest
+                username: _json_key
+            params:
+              A: blah
+              ARTIFACTORY_PASSWORD: ((artifactory.password))
+              ARTIFACTORY_URL: ((artifactory.url))
+              ARTIFACTORY_USERNAME: ((artifactory.username))
+              TEST_ROUTE: halfpipe-example-kotlin-dev-dev-CANDIDATE.some.random.domain.com
+            run:
+              path: /bin/sh
+              args:
+              - -c
+              - |
+                which bash > /dev/null
+                if [ $? != 0 ]; then
+                  echo "WARNING: Bash is not present in the docker image"
+                  echo "If your script depends on bash you will get a strange error message like:"
+                  echo "  sh: yourscript.sh: command not found"
+                  echo "To fix, make sure your docker image contains bash!"
+                  echo ""
+                  echo ""
+                fi
 
-              if [ -e /etc/alpine-release ]
-              then
-                echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
-                echo "There is a known issue where DNS resolving does not work as expected"
-                echo "https://github.com/gliderlabs/docker-alpine/issues/255"
-                echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
-                echo "we recommend debian:stretch-slim as an alternative"
-                echo ""
-                echo ""
-              fi
+                if [ -e /etc/alpine-release ]
+                then
+                  echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
+                  echo "There is a known issue where DNS resolving does not work as expected"
+                  echo "https://github.com/gliderlabs/docker-alpine/issues/255"
+                  echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
+                  echo "we recommend debian:stretch-slim as an alternative"
+                  echo ""
+                  echo ""
+                fi
 
-              export GIT_REVISION=`cat ../../.git/ref`
+                export GIT_REVISION=`cat ../../.git/ref`
 
-              ./smoke-test.sh
-              EXIT_STATUS=$?
-              if [ $EXIT_STATUS != 0 ] ; then
-                exit 1
-              fi
-            dir: git/e2e/deploy-cf
-          inputs:
-          - name: git
-          caches:
-          - path: ../../../var/halfpipe/cache
-          - path: ../../../halfpipe-cache
-        attempts: 1
+                ./smoke-test.sh
+                EXIT_STATUS=$?
+                if [ $EXIT_STATUS != 0 ] ; then
+                  exit 1
+                fi
+              dir: git/e2e/deploy-cf
+            inputs:
+            - name: git
+            caches:
+            - path: ../../../var/halfpipe/cache
+            - path: ../../../halfpipe-cache
+          attempts: 1
     timeout: 5m
   - put: cf halfpipe-promote
     resource: CF dev-api test dev
