fix docker deploy to cf + rolling deploy

diff --git a/e2e/deploy-cf-docker-image/expected-pipeline.yml b/e2e/deploy-cf-docker-image/expected-pipeline.yml
--- a/e2e/deploy-cf-docker-image/expected-pipeline.yml
+++ b/e2e/deploy-cf-docker-image/expected-pipeline.yml
@@ -18,12 +18,28 @@ resources:
     space: dev
     username: ((cloudfoundry.username-snpaas))
   check_every: 24h
+- name: rolling cf snpaas dev
+  type: rolling-deploy
+  source:
+    api: ((cloudfoundry.api-snpaas))
+    org: ((cloudfoundry.org-snpaas))
+    password: ((cloudfoundry.password-snpaas))
+    space: dev
+    username: ((cloudfoundry.username-snpaas))
+  check_every: 24h
 resource_types:
 - name: cf-resource
   type: registry-image
   source:
     password: ((halfpipe-gcr.private_key))
     repository: eu.gcr.io/halfpipe-io/cf-resource
+    tag: stable
+    username: _json_key
+- name: rolling-deploy
+  type: registry-image
+  source:
+    password: ((halfpipe-gcr.private_key))
+    repository: eu.gcr.io/halfpipe-io/cf-resource-v7
     tag: stable
     username: _json_key
 jobs:
@@ -98,6 +114,145 @@ jobs:
       - get: git
         passed:
         - deploy to cf simple
+        trigger: true
+        attempts: 2
+      fail_fast: true
+    timeout: 1h
+  - put: cf halfpipe-push
+    resource: CF snpaas dev
+    params:
+      command: halfpipe-push
+      dockerPassword: ((halfpipe-gcr.private_key))
+      dockerUsername: _json_key
+      gitRefPath: git/.git/ref
+      manifestPath: git/e2e/deploy-cf-docker-image/manifest.yml
+      testDomain: springernature.app
+      timeout: 1h
+    timeout: 1h
+    attempts: 2
+  - put: cf halfpipe-check
+    resource: CF snpaas dev
+    params:
+      command: halfpipe-check
+      manifestPath: git/e2e/deploy-cf-docker-image/manifest.yml
+      timeout: 1h
+    timeout: 1h
+    attempts: 2
+  - in_parallel:
+      steps:
+      - do:
+        - task: pre promote step
+          config:
+            platform: linux
+            image_resource:
+              type: registry-image
+              source:
+                password: ((halfpipe-gcr.private_key))
+                repository: eu.gcr.io/halfpipe-io/halfpipe-fly
+                tag: latest
+                username: _json_key
+            params:
+              A: blah
+              ARTIFACTORY_PASSWORD: ((artifactory.password))
+              ARTIFACTORY_URL: ((artifactory.url))
+              ARTIFACTORY_USERNAME: ((artifactory.username))
+              TEST_ROUTE: halfpipe-example-kotlin-dev-dev-CANDIDATE.springernature.app
+            run:
+              path: /bin/sh
+              args:
+              - -c
+              - |
+                which bash > /dev/null
+                if [ $? != 0 ]; then
+                  echo "WARNING: Bash is not present in the docker image"
+                  echo "If your script depends on bash you will get a strange error message like:"
+                  echo "  sh: yourscript.sh: command not found"
+                  echo "To fix, make sure your docker image contains bash!"
+                  echo ""
+                  echo ""
+                fi
+
+                if [ -e /etc/alpine-release ]
+                then
+                  echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
+                  echo "There is a known issue where DNS resolving does not work as expected"
+                  echo "https://github.com/gliderlabs/docker-alpine/issues/255"
+                  echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
+                  echo "we recommend debian:stretch-slim as an alternative"
+                  echo ""
+                  echo ""
+                fi
+
+                export GIT_REVISION=`cat ../../.git/ref`
+
+                ./smoke-test.sh
+                EXIT_STATUS=$?
+                if [ $EXIT_STATUS != 0 ] ; then
+                  exit 1
+                fi
+              dir: git/e2e/deploy-cf-docker-image
+            inputs:
+            - name: git
+            caches:
+            - path: ../../../var/halfpipe/cache
+            - path: ../../../halfpipe-cache
+          attempts: 1
+    timeout: 1h
+  - put: cf halfpipe-promote
+    resource: CF snpaas dev
+    params:
+      command: halfpipe-promote
+      manifestPath: git/e2e/deploy-cf-docker-image/manifest.yml
+      testDomain: springernature.app
+      timeout: 1h
+    timeout: 1h
+    attempts: 2
+- name: deploy to cf simple - rolling deploy
+  serial: true
+  build_log_retention:
+    builds: 5
+    minimum_succeeded_builds: 1
+  plan:
+  - in_parallel:
+      steps:
+      - get: git
+        passed:
+        - deploy to cf with pre promote
+        trigger: true
+        attempts: 2
+      fail_fast: true
+    timeout: 1h
+  - put: cf rolling deploy
+    resource: rolling cf snpaas dev
+    params:
+      command: halfpipe-rolling-deploy
+      dockerPassword: ((halfpipe-gcr.private_key))
+      dockerUsername: _json_key
+      gitRefPath: git/.git/ref
+      manifestPath: git/e2e/deploy-cf-docker-image/manifest.yml
+      timeout: 1h
+    timeout: 1h
+    attempts: 2
+- name: deploy to cf with pre promote - rolling deploy
+  serial: true
+  build_log_retention:
+    builds: 5
+    minimum_succeeded_builds: 1
+  ensure:
+    put: cf halfpipe-cleanup
+    resource: CF snpaas dev
+    params:
+      command: halfpipe-cleanup
+      manifestPath: git/e2e/deploy-cf-docker-image/manifest.yml
+      timeout: 1h
+    timeout: 1h
+    attempts: 2
+  plan:
+  - in_parallel:
+      steps:
+      - get: git
+        passed:
+        - deploy to cf simple - rolling deploy
         trigger: true
         attempts: 2
       fail_fast: true
