don't use new cdc script in actions as it doesn't run in the halfpipe-docker-compose image

diff --git a/e2e/actions/consumer-integration-test/workflowExpected.yml b/e2e/actions/consumer-integration-test/workflowExpected.yml
--- a/e2e/actions/consumer-integration-test/workflowExpected.yml
+++ b/e2e/actions/consumer-integration-test/workflowExpected.yml
@@ -22,14 +22,74 @@ defaults:
     working-directory: e2e/actions/consumer-integration-test
 concurrency: ${{ github.workflow }}
 jobs:
-  another-c-name:
-    name: another-c-name
+  c-name:
+    name: c-name
     runs-on: ee-runner
     timeout-minutes: 60
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
-    - name: another-c-name
+    - name: c-name
+      run: |
+        # write git key to file
+        echo "${CONSUMER_GIT_KEY}" > .gitkey
+        chmod 600 .gitkey
+
+        set -ex
+
+        # get current revision of consumer, revert to HEAD if not found
+        REVISION=$(curl -fsSL "${CONSUMER_HOST}/internal/version" | jq -r '.revision' || echo "")
+        if [ "${REVISION}" == "" ]; then
+          echo "Error fetching version of consumer from ${CONSUMER_HOST}/internal/version - using HEAD instead."
+          REVISION=HEAD
+        fi
+
+        # clone consumer into /scratch/consumer. dir may already exist when concourse restarts task
+        rm -rf /scratch/consumer
+        GIT_SSH_COMMAND="ssh -o StrictHostKeychecking=no -i .gitkey" git clone ${GIT_CLONE_OPTIONS} ${CONSUMER_GIT_URI} /scratch/consumer
+        cd /scratch/consumer/${CONSUMER_PATH}
+
+        # checkout revision
+        git checkout ${REVISION}
+
+        # run the tests with docker-compose
+        # note: old system reads CF manifest env vars and sets them all here
+        docker-compose pull ${DOCKER_COMPOSE_SERVICE:-code}
+        docker-compose run --no-deps \
+          --entrypoint "${CONSUMER_SCRIPT}" \
+          -e DEPENDENCY_NAME=${PROVIDER_NAME} \
+          -e ${PROVIDER_HOST_KEY}=${PROVIDER_HOST} \
+          -e CDC_CONSUMER_NAME=${CONSUMER_NAME} \
+          -e CDC_CONSUMER_VERSION=${REVISION} \
+          -e CDC_PROVIDER_NAME=${PROVIDER_NAME} \
+          -e CDC_PROVIDER_VERSION=${GIT_REVISION} \
+          -e K -e K1 \
+           \
+          ${DOCKER_COMPOSE_SERVICE:-code}
+      env:
+        CONSUMER_GIT_KEY: ${{ secrets.EE_GITHUB_PRIVATE_KEY }}
+        CONSUMER_GIT_URI: git@github.com:springernature/c-consumer
+        CONSUMER_HOST: c-host
+        CONSUMER_NAME: c-consumer
+        CONSUMER_PATH: ""
+        CONSUMER_SCRIPT: c-script
+        DOCKER_COMPOSE_SERVICE: potato
+        GIT_CLONE_OPTIONS: --depth 100
+        K: value
+        K1: value1
+        PROVIDER_HOST: p-host
+        PROVIDER_HOST_KEY: P_NAME_DEPLOYED_HOST
+        PROVIDER_NAME: p-name
+  c-name-covenant:
+    name: c-name-covenant
+    needs:
+    - c-name
+    runs-on: ee-runner
+    timeout-minutes: 60
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+    - name: c-name-covenant
       run: |
         # write git key to file
         echo "${CONSUMER_GIT_KEY}" > .gitkey
diff --git a/e2e/concourse/consumer-integration-test/pipelineExpected.yml b/e2e/concourse/consumer-integration-test/pipelineExpected.yml
--- a/e2e/concourse/consumer-integration-test/pipelineExpected.yml
+++ b/e2e/concourse/consumer-integration-test/pipelineExpected.yml
@@ -2,7 +2,7 @@
 jobs:
 - build_log_retention:
     minimum_succeeded_builds: 1
-  name: another-c-name
+  name: c-name
   plan:
   - attempts: 2
     get: git
@@ -61,6 +61,8 @@ jobs:
           export GIT_REVISION=`cat ../../../.git/ref`
 
           \docker login -u _json_key -p "$GCR_PRIVATE_KEY" https://eu.gcr.io
+
+
           export ENV_OPTIONS="-e ARTIFACTORY_PASSWORD -e ARTIFACTORY_URL -e ARTIFACTORY_USERNAME -e K -e K1 -e RUNNING_IN_CI"
           export VOLUME_OPTIONS="-v /var/halfpipe/cache:/var/halfpipe/cache -v /var/halfpipe/shared-cache:/var/halfpipe/shared-cache"
           /cdc.sh
@@ -71,7 +73,85 @@ jobs:
         dir: git/e2e/concourse/consumer-integration-test
         path: docker.sh
     privileged: true
-    task: another-c-name
+    task: c-name
+    timeout: 1h
+  serial: true
+- build_log_retention:
+    minimum_succeeded_builds: 1
+  name: c-name-covenant
+  plan:
+  - attempts: 2
+    get: git
+    passed:
+    - c-name
+    timeout: 15m
+    trigger: true
+  - config:
+      caches:
+      - path: ../../../var/halfpipe/cache
+      - path: ../../../halfpipe-cache
+      image_resource:
+        source:
+          password: ((halfpipe-gcr.private_key))
+          registry_mirror:
+            host: eu-mirror.gcr.io
+          repository: eu.gcr.io/halfpipe-io/halfpipe-docker-compose
+          tag: stable
+          username: _json_key
+        type: registry-image
+      inputs:
+      - name: git
+      params:
+        ARTIFACTORY_PASSWORD: ((artifactory.password))
+        ARTIFACTORY_URL: ((artifactory.url))
+        ARTIFACTORY_USERNAME: ((artifactory.username))
+        CONSUMER_GIT_KEY: ((halfpipe-github.private_key))
+        CONSUMER_GIT_URI: git@github.com:springernature/c-consumer
+        CONSUMER_HOST: c-host
+        CONSUMER_NAME: c-consumer
+        CONSUMER_PATH: ""
+        CONSUMER_SCRIPT: c-script
+        DOCKER_COMPOSE_SERVICE: potato
+        GCR_PRIVATE_KEY: ((halfpipe-gcr.private_key))
+        GIT_CLONE_OPTIONS: --depth 100
+        K: value
+        K1: value1
+        PROVIDER_HOST: p-host
+        PROVIDER_HOST_KEY: P_NAME_DEPLOYED_HOST
+        PROVIDER_NAME: p-name
+        RUNNING_IN_CI: "true"
+      platform: linux
+      run:
+        args:
+        - -c
+        - |
+          if [ -e /etc/alpine-release ]
+          then
+            echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
+            echo "There is a known issue where DNS resolving does not work as expected"
+            echo "https://github.com/gliderlabs/docker-alpine/issues/255"
+            echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
+            echo "we recommend debian:buster-slim as an alternative"
+            echo ""
+            echo ""
+          fi
+
+          export GIT_REVISION=`cat ../../../.git/ref`
+
+          \docker login -u _json_key -p "$GCR_PRIVATE_KEY" https://eu.gcr.io
+
+
+          export ENV_OPTIONS="-e ARTIFACTORY_PASSWORD -e ARTIFACTORY_URL -e ARTIFACTORY_USERNAME -e K -e K1 -e RUNNING_IN_CI"
+          export VOLUME_OPTIONS="-v /var/halfpipe/cache:/var/halfpipe/cache -v /var/halfpipe/shared-cache:/var/halfpipe/shared-cache"
+          /cdc.sh
+          EXIT_STATUS=$?
+          if [ $EXIT_STATUS != 0 ] ; then
+            exit 1
+          fi
+        dir: git/e2e/concourse/consumer-integration-test
+        path: docker.sh
+    privileged: true
+    task: c-name-covenant
     timeout: 1h
   serial: true
 resources:
