first working version of new parallel tasks

diff --git a/e2e/parallel/expected-pipeline.yml b/e2e/parallel/expected-pipeline.yml
--- a/e2e/parallel/expected-pipeline.yml
+++ b/e2e/parallel/expected-pipeline.yml
@@ -196,17 +196,17 @@ jobs:
       - aggregate:
           - get: git
             passed:
-              - parallel 1
-              - parallel 2
+              - test parallel 1
+              - test parallel 2
             params:
               depth: 1
           - get: version
             passed:
-              - parallel 1
-              - parallel 2
+              - test parallel 1
+              - test parallel 2
             trigger: true
         timeout: 1h
-      - task: test parallel 2
+      - task: test parallel 3
         config:
           platform: linux
           image_resource:
@@ -267,17 +267,17 @@ jobs:
       - aggregate:
           - get: git
             passed:
-              - parallel 1
-              - parallel 2
+              - test parallel 1
+              - test parallel 2
             params:
               depth: 1
           - get: version
             passed:
-              - parallel 1
-              - parallel 2
+              - test parallel 1
+              - test parallel 2
             trigger: true
         timeout: 1h
-      - task: test parallel 2
+      - task: test parallel 4
         config:
           platform: linux
           image_resource:
@@ -332,20 +332,229 @@ jobs:
             - path: ../../../halfpipe-cache
         timeout: 1h
         attempts: 1
+  - name: not parallel
+      serial: true
+      plan:
+        - aggregate:
+            - get: git
+              passed:
+                - test parallel 3
+                - test parallel 4
+              params:
+                depth: 1
+            - get: version
+              passed:
+                - test parallel 3
+                - test parallel 4
+              trigger: true
+          timeout: 1h
+        - task: not parallel
+          config:
+            platform: linux
+            image_resource:
+          type: registry-image
+            source:
+              repository: alpine
+              tag: test
+            params:
+              ARTIFACTORY_PASSWORD: ((artifactory.password))
+              ARTIFACTORY_URL: ((artifactory.url))
+              ARTIFACTORY_USERNAME: ((artifactory.username))
+            run:
+              path: /bin/sh
+              args:
+                - -c
+                - |
+                  which bash > /dev/null
+                  if [ $? != 0 ]; then
+                    echo "WARNING: Bash is not present in the docker image"
+                    echo "If your script depends on bash you will get a strange error message like:"
+                    echo "  sh: yourscript.sh: command not found"
+                    echo "To fix, make sure your docker image contains bash!"
+                    echo ""
+                    echo ""
+                  fi
+
+                  if [ -e /etc/alpine-release ]
+                  then
+                    echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
+                    echo "There is a known issue where DNS resolving does not work as expected"
+                    echo "https://github.com/gliderlabs/docker-alpine/issues/255"
+                    echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
+                    echo "we recommend debian:stretch-slim as an alternative"
+                    echo ""
+                    echo ""
+                  fi
+
+                  export GIT_REVISION=`cat ../../.git/ref`
+                  export BUILD_VERSION=`cat ../../../version/version`
+
+                  ./a
+                  EXIT_STATUS=$?
+                  if [ $EXIT_STATUS != 0 ] ; then
+                    exit 1
+                  fi
+              dir: git/e2e/parallel
+            inputs:
+              - name: git
+              - name: version
+            caches:
+              - path: ../../../var/halfpipe/cache
+              - path: ../../../halfpipe-cache
+          timeout: 1h
+          attempts: 1
+  - name: test parallel 5
+      serial: true
+      plan:
+        - aggregate:
+            - get: git
+              passed:
+                - not parallel
+              params:
+                depth: 1
+            - get: version
+              passed:
+                - not parallel
+              trigger: true
+          timeout: 1h
+        - task: test parallel 5
+          config:
+            platform: linux
+            image_resource:
+          type: registry-image
+            source:
+              repository: alpine
+              tag: test
+            params:
+              ARTIFACTORY_PASSWORD: ((artifactory.password))
+              ARTIFACTORY_URL: ((artifactory.url))
+              ARTIFACTORY_USERNAME: ((artifactory.username))
+            run:
+              path: /bin/sh
+              args:
+                - -c
+                - |
+                  which bash > /dev/null
+                  if [ $? != 0 ]; then
+                    echo "WARNING: Bash is not present in the docker image"
+                    echo "If your script depends on bash you will get a strange error message like:"
+                    echo "  sh: yourscript.sh: command not found"
+                    echo "To fix, make sure your docker image contains bash!"
+                    echo ""
+                    echo ""
+                  fi
+
+                  if [ -e /etc/alpine-release ]
+                  then
+                    echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
+                    echo "There is a known issue where DNS resolving does not work as expected"
+                    echo "https://github.com/gliderlabs/docker-alpine/issues/255"
+                    echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
+                    echo "we recommend debian:stretch-slim as an alternative"
+                    echo ""
+                    echo ""
+                  fi
+
+                  export GIT_REVISION=`cat ../../.git/ref`
+                  export BUILD_VERSION=`cat ../../../version/version`
+
+                  ./a
+                  EXIT_STATUS=$?
+                  if [ $EXIT_STATUS != 0 ] ; then
+                    exit 1
+                  fi
+              dir: git/e2e/parallel
+            inputs:
+              - name: git
+              - name: version
+            caches:
+              - path: ../../../var/halfpipe/cache
+              - path: ../../../halfpipe-cache
+          timeout: 1h
+          attempts: 1
+  - name: test parallel 6
+      serial: true
+      plan:
+        - aggregate:
+            - get: git
+              passed:
+                - not parallel
+              params:
+                depth: 1
+            - get: version
+              passed:
+                - not parallel
+              trigger: true
+          timeout: 1h
+        - task: test parallel 6
+          config:
+            platform: linux
+            image_resource:
+          type: registry-image
+            source:
+              repository: alpine
+              tag: test
+            params:
+              ARTIFACTORY_PASSWORD: ((artifactory.password))
+              ARTIFACTORY_URL: ((artifactory.url))
+              ARTIFACTORY_USERNAME: ((artifactory.username))
+            run:
+              path: /bin/sh
+              args:
+                - -c
+                - |
+                  which bash > /dev/null
+                  if [ $? != 0 ]; then
+                    echo "WARNING: Bash is not present in the docker image"
+                    echo "If your script depends on bash you will get a strange error message like:"
+                    echo "  sh: yourscript.sh: command not found"
+                    echo "To fix, make sure your docker image contains bash!"
+                    echo ""
+                    echo ""
+                  fi
+
+                  if [ -e /etc/alpine-release ]
+                  then
+                    echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
+                    echo "There is a known issue where DNS resolving does not work as expected"
+                    echo "https://github.com/gliderlabs/docker-alpine/issues/255"
+                    echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
+                    echo "we recommend debian:stretch-slim as an alternative"
+                    echo ""
+                    echo ""
+                  fi
+
+                  export GIT_REVISION=`cat ../../.git/ref`
+                  export BUILD_VERSION=`cat ../../../version/version`
+
+                  ./a
+                  EXIT_STATUS=$?
+                  if [ $EXIT_STATUS != 0 ] ; then
+                    exit 1
+                  fi
+              dir: git/e2e/parallel
+            inputs:
+              - name: git
+              - name: version
+            caches:
+              - path: ../../../var/halfpipe/cache
+              - path: ../../../halfpipe-cache
+          timeout: 1h
+          attempts: 1
   - name: after parallel
     serial: true
     plan:
       - aggregate:
           - get: git
             passed:
-              - test parallel 1
-              - test parallel 2
+              - test parallel 5
+              - test parallel 6
             params:
               depth: 1
           - get: version
             passed:
-              - test parallel 1
-              - test parallel 2
+              - test parallel 5
+              - test parallel 6
             trigger: true
         timeout: 1h
       - task: after parallel
