fix cf mapper when path to manifest starts ../

diff --git a/e2e/concourse/deploy-cf-with-artefact/pipelineExpected.yml b/e2e/concourse/deploy-cf-with-artefact/pipelineExpected.yml
--- a/e2e/concourse/deploy-cf-with-artefact/pipelineExpected.yml
+++ b/e2e/concourse/deploy-cf-with-artefact/pipelineExpected.yml
@@ -92,6 +92,17 @@ jobs:
   serial: true
 - build_log_retention:
     minimum_succeeded_builds: 1
+  ensure:
+    attempts: 2
+    no_get: true
+    params:
+      cliVersion: cf7
+      command: halfpipe-cleanup
+      manifestPath: git/e2e/concourse/deploy-cf/manifest.yml
+      timeout: 5m
+    put: halfpipe-cleanup
+    resource: cf-dev-api-halfpipe-team-dev
+    timeout: 5m
   name: deploy to cf
   plan:
   - attempts: 2
@@ -134,20 +145,101 @@ jobs:
       params:
         cliVersion: cf7
         command: halfpipe-logs
-        manifestPath: git/e2e/concourse/deploy-cf-with-artefact/manifest.yml
+        manifestPath: git/e2e/concourse/deploy-cf/manifest.yml
       put: cf-logs
       resource: cf-dev-api-halfpipe-team-dev
     params:
       appPath: artifacts/e2e/concourse/deploy-cf-with-artefact/build/linux/binary
       cliVersion: cf7
-      command: halfpipe-all
+      command: halfpipe-push
       gitRefPath: git/.git/ref
       gitUri: git@github.com:springernature/halfpipe.git
-      manifestPath: git/e2e/concourse/deploy-cf-with-artefact/manifest.yml
+      manifestPath: git/e2e/concourse/deploy-cf/manifest.yml
       team: halfpipe-team
       testDomain: some.random.domain.com
       timeout: 5m
-    put: halfpipe-all
+    put: halfpipe-push
+    resource: cf-dev-api-halfpipe-team-dev
+    timeout: 5m
+  - attempts: 2
+    no_get: true
+    params:
+      cliVersion: cf7
+      command: halfpipe-check
+      manifestPath: git/e2e/concourse/deploy-cf/manifest.yml
+      timeout: 5m
+    put: halfpipe-check
+    resource: cf-dev-api-halfpipe-team-dev
+    timeout: 5m
+  - config:
+      caches:
+      - path: ../../../var/halfpipe/cache
+      - path: ../../../halfpipe-cache
+      image_resource:
+        name: ""
+        source:
+          password: ((halfpipe-gcr.private_key))
+          registry_mirror:
+            host: eu-mirror.gcr.io
+          repository: eu.gcr.io/halfpipe-io/halfpipe-fly
+          tag: latest
+          username: _json_key
+        type: registry-image
+      inputs:
+      - name: git
+      params:
+        A: blah
+        ARTIFACTORY_PASSWORD: ((artifactory.password))
+        ARTIFACTORY_URL: ((artifactory.url))
+        ARTIFACTORY_USERNAME: ((artifactory.username))
+        RUNNING_IN_CI: "true"
+        TEST_ROUTE: halfpipe-example-kotlin-dev-dev-CANDIDATE.some.random.domain.com
+      platform: linux
+      run:
+        args:
+        - -c
+        - |
+          if ! which bash > /dev/null && [ "$SUPPRESS_BASH_WARNING" != "true" ]; then
+            echo "WARNING: Bash is not present in the docker image"
+            echo "If your script depends on bash you will get a strange error message like:"
+            echo "  sh: yourscript.sh: command not found"
+            echo "To fix, make sure your docker image contains bash!"
+            echo "Or if you are sure you don't need bash you can suppress this warning by setting the environment variable \"SUPPRESS_BASH_WARNING\" to \"true\"."
+            echo ""
+            echo ""
+          fi
+
+          if [ -e /etc/alpine-release ]
+          then
+            echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
+            echo "There is a known issue where DNS resolving does not work as expected"
+            echo "https://github.com/gliderlabs/docker-alpine/issues/255"
+            echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
+            echo "we recommend debian:buster-slim as an alternative"
+            echo ""
+            echo ""
+          fi
+
+          export GIT_REVISION=`cat ../../../.git/ref`
+
+          ./smoke-test.sh
+          EXIT_STATUS=$?
+          if [ $EXIT_STATUS != 0 ] ; then
+            exit 1
+          fi
+        dir: git/e2e/concourse/deploy-cf-with-artefact
+        path: /bin/sh
+    task: pre-promote-step
+    timeout: 1h
+  - attempts: 2
+    no_get: true
+    params:
+      cliVersion: cf7
+      command: halfpipe-promote
+      manifestPath: git/e2e/concourse/deploy-cf/manifest.yml
+      testDomain: some.random.domain.com
+      timeout: 5m
+    put: halfpipe-promote
     resource: cf-dev-api-halfpipe-team-dev
     timeout: 5m
   serial: true
