Dirty duplication for pre-promote stuff for rolling deployments

diff --git a/e2e/deploy-cf-rolling/expected-pipeline.yml b/e2e/deploy-cf-rolling/expected-pipeline.yml
--- a/e2e/deploy-cf-rolling/expected-pipeline.yml
+++ b/e2e/deploy-cf-rolling/expected-pipeline.yml
@@ -37,6 +37,78 @@ jobs:
         attempts: 2
       fail_fast: true
     timeout: 5m
+  - put: deploy test app
+    resource: rolling cf dev-api engineering-enablement dev
+    params:
+      appPath: git/e2e/deploy-cf-rolling
+      command: halfpipe-push
+      gitRefPath: git/.git/ref
+      instances: "1"
+      manifestPath: git/e2e/deploy-cf-rolling/manifest.yml
+      testDomain: some.random.domain.com
+      timeout: 5m
+    timeout: 5m
+    attempts: 2
+  - in_parallel:
+      steps:
+      - do:
+        - task: pre promote step
+          config:
+            platform: linux
+            image_resource:
+              type: registry-image
+              source:
+                password: ((halfpipe-gcr.private_key))
+                repository: eu.gcr.io/halfpipe-io/halfpipe-fly
+                tag: latest
+                username: _json_key
+            params:
+              A: blah
+              ARTIFACTORY_PASSWORD: ((artifactory.password))
+              ARTIFACTORY_URL: ((artifactory.url))
+              ARTIFACTORY_USERNAME: ((artifactory.username))
+              TEST_ROUTE: halfpipe-example-kotlin-dev-dev-CANDIDATE.some.random.domain.com
+            run:
+              path: /bin/sh
+              args:
+              - -c
+              - |
+                which bash > /dev/null
+                if [ $? != 0 ]; then
+                  echo "WARNING: Bash is not present in the docker image"
+                  echo "If your script depends on bash you will get a strange error message like:"
+                  echo "  sh: yourscript.sh: command not found"
+                  echo "To fix, make sure your docker image contains bash!"
+                  echo ""
+                  echo ""
+                fi
+
+                if [ -e /etc/alpine-release ]
+                then
+                  echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
+                  echo "There is a known issue where DNS resolving does not work as expected"
+                  echo "https://github.com/gliderlabs/docker-alpine/issues/255"
+                  echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
+                  echo "we recommend debian:stretch-slim as an alternative"
+                  echo ""
+                  echo ""
+                fi
+
+                export GIT_REVISION=`cat ../../.git/ref`
+
+                ./smoke-test.sh
+                EXIT_STATUS=$?
+                if [ $EXIT_STATUS != 0 ] ; then
+                  exit 1
+                fi
+              dir: git/e2e/deploy-cf-rolling
+            inputs:
+            - name: git
+            caches:
+            - path: ../../../var/halfpipe/cache
+            - path: ../../../halfpipe-cache
+          attempts: 1
+    timeout: 5m
   - put: cf rolling deploy
     resource: rolling cf dev-api engineering-enablement dev
     params:
