add deployment status script to deploy-katee task

diff --git a/e2e/concourse/deploy-katee/pipelineExpected.yml b/e2e/concourse/deploy-katee/pipelineExpected.yml
--- a/e2e/concourse/deploy-katee/pipelineExpected.yml
+++ b/e2e/concourse/deploy-katee/pipelineExpected.yml
@@ -114,6 +114,10 @@ jobs:
       - name: version
       params:
         DOCKER_TAG: buildVersion
+        ENV1: "1234"
+        ENV2: ((secret.something))
+        ENV3: '{"a": "b", "c": "d"}'
+        ENV4: ((another.secret))
         KATEE_APPFILE: vela.yaml
         KATEE_APPLICATION_NAME: BLAHBLAH
         KATEE_GKE_CREDENTIALS: ((katee-halfpipe-team-service-account-prod.key))
@@ -148,13 +152,19 @@ jobs:
           export GIT_REVISION=`cat ../../../.git/ref`
           export BUILD_VERSION=`cat ../../../../version/version`
 
-          \echo "Running vela up...";
+          \echo "Running vela up..."
+
           if [ "$DOCKER_TAG" == "gitref" ]
           then
-            export KATEE_APPLICATION_IMAGE=$KATEE_IMAGE:$GIT_REVISION;
+            export TAG="$GIT_REVISION"
           else
-            export KATEE_APPLICATION_IMAGE=$KATEE_IMAGE:$BUILD_VERSION;
-          fi; /exe vela up -f $KATEE_APPFILE --publish-version $DOCKER_TAG
+            export TAG="$BUILD_VERSION"
+          fi
+
+          export KATEE_APPLICATION_IMAGE=$KATEE_IMAGE:$TAG
+
+          /exe vela up -f $KATEE_APPFILE --publish-version $TAG
+
           EXIT_STATUS=$?
           if [ $EXIT_STATUS != 0 ] ; then
             exit 1
@@ -163,6 +173,74 @@ jobs:
         path: /bin/sh
     task: deploy-to-katee
     timeout: 1h
+  - attempts: 2
+    config:
+      caches:
+      - path: ../../../var/halfpipe/cache
+      - path: ../../../halfpipe-cache
+      image_resource:
+        source:
+          password: ((halfpipe-gcr.private_key))
+          registry_mirror:
+            host: eu-mirror.gcr.io
+          repository: eu.gcr.io/halfpipe-io/ee-katee-vela-cli
+          tag: latest
+          username: _json_key
+        type: registry-image
+      inputs:
+      - name: git
+      - name: version
+      params:
+        APPLICATION_NAME: BLAHBLAH
+        DOCKER_TAG: buildVersion
+        KATEE_GKE_CREDENTIALS: ((katee-halfpipe-team-service-account-prod.key))
+        KATEE_TEAM: halfpipe-team
+      platform: linux
+      run:
+        args:
+        - -c
+        - |
+          if ! which bash > /dev/null && [ "$SUPPRESS_BASH_WARNING" != "true" ]; then
+            echo "WARNING: Bash is not present in the docker image"
+            echo "If your script depends on bash you will get a strange error message like:"
+            echo "  sh: yourscript.sh: command not found"
+            echo "To fix, make sure your docker image contains bash!"
+            echo "Or if you are sure you don't need bash you can suppress this warning by setting the environment variable \"SUPPRESS_BASH_WARNING\" to \"true\"."
+            echo ""
+            echo ""
+          fi
+
+          if [ -e /etc/alpine-release ]
+          then
+            echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
+            echo "There is a known issue where DNS resolving does not work as expected"
+            echo "https://github.com/gliderlabs/docker-alpine/issues/255"
+            echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
+            echo "we recommend debian:buster-slim as an alternative"
+            echo ""
+            echo ""
+          fi
+
+          export GIT_REVISION=`cat ../../../.git/ref`
+          export BUILD_VERSION=`cat ../../../../version/version`
+
+          \echo "Checking Deployment Status.."
+          if [ "$DOCKER_TAG" == "gitref" ]
+          then
+            export PUBLISHED_VERSION=$GIT_REVISION
+          else
+            export PUBLISHED_VERSION=$BUILD_VERSION
+          fi
+
+          /exe deployment-status katee-$KATEE_TEAM $APPLICATION_NAME $PUBLISHED_VERSION
+          EXIT_STATUS=$?
+          if [ $EXIT_STATUS != 0 ] ; then
+            exit 1
+          fi
+        dir: git/e2e/concourse/deploy-katee
+        path: /bin/sh
+    task: check-deployment-status
+    timeout: ""
   serial: true
 resource_types:
 - check_every: 24h
