Dont use do in pre_promote tasks and dont wrap in a paralell if only one task

diff --git a/e2e/artifacts/pipelineExpected.yml b/e2e/artifacts/pipelineExpected.yml
--- a/e2e/artifacts/pipelineExpected.yml
+++ b/e2e/artifacts/pipelineExpected.yml
@@ -273,71 +273,66 @@ jobs:
     put: halfpipe-check
     resource: cf-snpaas-pe-staging
     timeout: 1h
-  - in_parallel:
-      fail_fast: true
-      steps:
-      - do:
-        - attempts: 1
-          config:
-            caches:
-            - path: ../../../var/halfpipe/cache
-            - path: ../../../halfpipe-cache
-            image_resource:
-              source:
-                password: ((halfpipe-gcr.private_key))
-                repository: eu.gcr.io/halfpipe-io/halfpipe-fly
-                tag: latest
-                username: _json_key
-              type: registry-image
-            inputs:
-            - name: git
-            - name: artifacts
-            params:
-              A: blah
-              ARTIFACTORY_PASSWORD: ((artifactory.password))
-              ARTIFACTORY_URL: ((artifactory.url))
-              ARTIFACTORY_USERNAME: ((artifactory.username))
-              TEST_ROUTE: halfpipe-example-kotlin-dev-staging-CANDIDATE.springernature.app
-            platform: linux
-            run:
-              args:
-              - -c
-              - |
-                if ! which bash > /dev/null && [ "$SUPPRESS_BASH_WARNING" != "true" ]; then
-                  echo "WARNING: Bash is not present in the docker image"
-                  echo "If your script depends on bash you will get a strange error message like:"
-                  echo "  sh: yourscript.sh: command not found"
-                  echo "To fix, make sure your docker image contains bash!"
-                  echo "Or if you are sure you don't need bash you can suppress this warning by setting the environment variable \"SUPPRESS_BASH_WARNING\" to \"true\"."
-                  echo ""
-                  echo ""
-                fi
+  - attempts: 1
+    config:
+      caches:
+      - path: ../../../var/halfpipe/cache
+      - path: ../../../halfpipe-cache
+      image_resource:
+        source:
+          password: ((halfpipe-gcr.private_key))
+          repository: eu.gcr.io/halfpipe-io/halfpipe-fly
+          tag: latest
+          username: _json_key
+        type: registry-image
+      inputs:
+      - name: git
+      - name: artifacts
+      params:
+        A: blah
+        ARTIFACTORY_PASSWORD: ((artifactory.password))
+        ARTIFACTORY_URL: ((artifactory.url))
+        ARTIFACTORY_USERNAME: ((artifactory.username))
+        TEST_ROUTE: halfpipe-example-kotlin-dev-staging-CANDIDATE.springernature.app
+      platform: linux
+      run:
+        args:
+        - -c
+        - |
+          if ! which bash > /dev/null && [ "$SUPPRESS_BASH_WARNING" != "true" ]; then
+            echo "WARNING: Bash is not present in the docker image"
+            echo "If your script depends on bash you will get a strange error message like:"
+            echo "  sh: yourscript.sh: command not found"
+            echo "To fix, make sure your docker image contains bash!"
+            echo "Or if you are sure you don't need bash you can suppress this warning by setting the environment variable \"SUPPRESS_BASH_WARNING\" to \"true\"."
+            echo ""
+            echo ""
+          fi
 
-                if [ -e /etc/alpine-release ]
-                then
-                  echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
-                  echo "There is a known issue where DNS resolving does not work as expected"
-                  echo "https://github.com/gliderlabs/docker-alpine/issues/255"
-                  echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
-                  echo "we recommend debian:buster-slim as an alternative"
-                  echo ""
-                  echo ""
-                fi
+          if [ -e /etc/alpine-release ]
+          then
+            echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
+            echo "There is a known issue where DNS resolving does not work as expected"
+            echo "https://github.com/gliderlabs/docker-alpine/issues/255"
+            echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
+            echo "we recommend debian:buster-slim as an alternative"
+            echo ""
+            echo ""
+          fi
 
-                # Copying in artifacts from previous task
-                cp -r ../../../artifacts/. ../..
+          # Copying in artifacts from previous task
+          cp -r ../../../artifacts/. ../..
 
-                export GIT_REVISION=`cat ../../.git/ref`
+          export GIT_REVISION=`cat ../../.git/ref`
 
-                ./a
-                EXIT_STATUS=$?
-                if [ $EXIT_STATUS != 0 ] ; then
-                  exit 1
-                fi
-              dir: git/e2e/artifacts
-              path: /bin/sh
-          task: run-a
-          timeout: 1h
+          ./a
+          EXIT_STATUS=$?
+          if [ $EXIT_STATUS != 0 ] ; then
+            exit 1
+          fi
+        dir: git/e2e/artifacts
+        path: /bin/sh
+    task: run-a
     timeout: 1h
   - attempts: 2
     params:
diff --git a/e2e/deploy-cf-rolling/pipelineExpected.yml b/e2e/deploy-cf-rolling/pipelineExpected.yml
--- a/e2e/deploy-cf-rolling/pipelineExpected.yml
+++ b/e2e/deploy-cf-rolling/pipelineExpected.yml
@@ -49,68 +49,63 @@ jobs:
     put: deploy-test-app
     resource: rolling-cf-dev-api-halfpipe-team-dev
     timeout: 5m
-  - in_parallel:
-      fail_fast: true
-      steps:
-      - do:
-        - attempts: 1
-          config:
-            caches:
-            - path: ../../../var/halfpipe/cache
-            - path: ../../../halfpipe-cache
-            image_resource:
-              source:
-                password: ((halfpipe-gcr.private_key))
-                repository: eu.gcr.io/halfpipe-io/halfpipe-fly
-                tag: latest
-                username: _json_key
-              type: registry-image
-            inputs:
-            - name: git
-            params:
-              A: blah
-              ARTIFACTORY_PASSWORD: ((artifactory.password))
-              ARTIFACTORY_URL: ((artifactory.url))
-              ARTIFACTORY_USERNAME: ((artifactory.username))
-              TEST_ROUTE: halfpipe-example-kotlin-dev-dev-CANDIDATE.some.random.domain.com
-            platform: linux
-            run:
-              args:
-              - -c
-              - |
-                if ! which bash > /dev/null && [ "$SUPPRESS_BASH_WARNING" != "true" ]; then
-                  echo "WARNING: Bash is not present in the docker image"
-                  echo "If your script depends on bash you will get a strange error message like:"
-                  echo "  sh: yourscript.sh: command not found"
-                  echo "To fix, make sure your docker image contains bash!"
-                  echo "Or if you are sure you don't need bash you can suppress this warning by setting the environment variable \"SUPPRESS_BASH_WARNING\" to \"true\"."
-                  echo ""
-                  echo ""
-                fi
+  - attempts: 1
+    config:
+      caches:
+      - path: ../../../var/halfpipe/cache
+      - path: ../../../halfpipe-cache
+      image_resource:
+        source:
+          password: ((halfpipe-gcr.private_key))
+          repository: eu.gcr.io/halfpipe-io/halfpipe-fly
+          tag: latest
+          username: _json_key
+        type: registry-image
+      inputs:
+      - name: git
+      params:
+        A: blah
+        ARTIFACTORY_PASSWORD: ((artifactory.password))
+        ARTIFACTORY_URL: ((artifactory.url))
+        ARTIFACTORY_USERNAME: ((artifactory.username))
+        TEST_ROUTE: halfpipe-example-kotlin-dev-dev-CANDIDATE.some.random.domain.com
+      platform: linux
+      run:
+        args:
+        - -c
+        - |
+          if ! which bash > /dev/null && [ "$SUPPRESS_BASH_WARNING" != "true" ]; then
+            echo "WARNING: Bash is not present in the docker image"
+            echo "If your script depends on bash you will get a strange error message like:"
+            echo "  sh: yourscript.sh: command not found"
+            echo "To fix, make sure your docker image contains bash!"
+            echo "Or if you are sure you don't need bash you can suppress this warning by setting the environment variable \"SUPPRESS_BASH_WARNING\" to \"true\"."
+            echo ""
+            echo ""
+          fi
 
-                if [ -e /etc/alpine-release ]
-                then
-                  echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
-                  echo "There is a known issue where DNS resolving does not work as expected"
-                  echo "https://github.com/gliderlabs/docker-alpine/issues/255"
-                  echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
-                  echo "we recommend debian:buster-slim as an alternative"
-                  echo ""
-                  echo ""
-                fi
+          if [ -e /etc/alpine-release ]
+          then
+            echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
+            echo "There is a known issue where DNS resolving does not work as expected"
+            echo "https://github.com/gliderlabs/docker-alpine/issues/255"
+            echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
+            echo "we recommend debian:buster-slim as an alternative"
+            echo ""
+            echo ""
+          fi
 
-                export GIT_REVISION=`cat ../../.git/ref`
+          export GIT_REVISION=`cat ../../.git/ref`
 
-                ./smoke-test.sh
-                EXIT_STATUS=$?
-                if [ $EXIT_STATUS != 0 ] ; then
-                  exit 1
-                fi
-              dir: git/e2e/deploy-cf-rolling
-              path: /bin/sh
-          task: pre-promote-step
-          timeout: 1h
-    timeout: 5m
+          ./smoke-test.sh
+          EXIT_STATUS=$?
+          if [ $EXIT_STATUS != 0 ] ; then
+            exit 1
+          fi
+        dir: git/e2e/deploy-cf-rolling
+        path: /bin/sh
+    task: pre-promote-step
+    timeout: 1h
   - attempts: 2
     params:
       appPath: git/e2e/deploy-cf-rolling
