working deploy-katee task for github actions

diff --git a/e2e/actions/deploy-katee/workflowExpected.yml b/e2e/actions/deploy-katee/workflowExpected.yml
--- a/e2e/actions/deploy-katee/workflowExpected.yml
+++ b/e2e/actions/deploy-katee/workflowExpected.yml
@@ -3,10 +3,10 @@ name: pipeline-name
 "on":
   push:
     branches:
-      - main
+    - main
     paths:
-      - e2e/actions/deploy-cf**
-      - .github/workflows/pipeline-name.yml
+    - e2e/actions/deploy-katee**
+    - .github/workflows/pipeline-name.yml
   workflow_dispatch: {}
 env:
   ARTIFACTORY_PASSWORD: ${{ secrets.EE_ARTIFACTORY_PASSWORD }}
@@ -19,21 +19,139 @@ env:
   VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
 defaults:
   run:
-    working-directory: e2e/actions/deploy-cf
+    working-directory: e2e/actions/deploy-katee
 concurrency: ${{ github.workflow }}
 jobs:
-  katee-deploy:
-    uses: springernature/ee-github-actions/.github/workflows/katee-deploy-workflow.yml@main
-    secrets: inherit
-    with:
-      team: engineering-enablement
-      applicationName: book-product-page
-      buildVersion: 0.0.${{ github.run_number }}
-
-      # optional
-      imageScanSeverity: SKIP
-      applicationRoot: katee-app
-      environment: live
-      url: https://ee-test-actions.public.springernature.app
-      vaultEnvVars: |
-        springernature/data/engineering-enablement/cloudfoundry-test user | VERY_SECRET
+  push_default:
+    name: Push default
+    runs-on: ee-runner
+    timeout-minutes: 60
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
+      with:
+        submodules: recursive
+        ssh-key: ${{ secrets.EE_GITHUB_PRIVATE_KEY }}
+    - name: Build Image
+      uses: docker/build-push-action@v3
+      with:
+        context: e2e/actions/deploy-katee
+        file: e2e/actions/deploy-katee/Dockerfile
+        push: false
+        tags: |
+          eu.gcr.io/halfpipe-io/halfpipe-team/someImage:latest
+          eu.gcr.io/halfpipe-io/halfpipe-team/someImage:${{ env.BUILD_VERSION }}
+        build-args: |
+          ARTIFACTORY_PASSWORD=${{ secrets.EE_ARTIFACTORY_PASSWORD }}
+          ARTIFACTORY_URL=${{ secrets.EE_ARTIFACTORY_URL }}
+          ARTIFACTORY_USERNAME=${{ secrets.EE_ARTIFACTORY_USERNAME }}
+          BUILD_VERSION=2.${{ github.run_number }}.0
+          GIT_REVISION=${{ github.sha }}
+          RUNNING_IN_CI=true
+          VAULT_ROLE_ID=${{ secrets.VAULT_ROLE_ID }}
+          VAULT_SECRET_ID=${{ secrets.VAULT_SECRET_ID }}
+    - name: gCloud Auth
+      uses: google-github-actions/auth@v0
+      with:
+        credentials_json: ${{ secrets.EE_GCR_PRIVATE_KEY }}
+    - name: gCloud Setup
+      uses: google-github-actions/setup-gcloud@v0
+      with:
+        project_id: halfpipe-io
+        install_components: local-extract
+    - name: Scan image for vulnerabilities
+      run: |-
+        SEVERITY=$(echo "$SEVERITY" | tr '[:lower:]' '[:upper:]')
+        [[ "$SEVERITY" = "SKIP" ]] && echo 'Skipping vulnerability check' && exit 0
+        [[ "$SEVERITY" = "HIGH" ]] && SEVERITY="CRITICAL|HIGH"
+        [[ "$SEVERITY" = "MEDIUM" ]] && SEVERITY="CRITICAL|HIGH|MEDIUM"
+        [[ "$SEVERITY" = "LOW" ]] && SEVERITY="CRITICAL|HIGH|MEDIUM|LOW"
+        gcloud artifacts docker images scan eu.gcr.io/halfpipe-io/halfpipe-team/someImage:${{ env.BUILD_VERSION }} --location=europe --additional-package-types=GO,MAVEN --format='value(response.scan)' > /tmp/image-scan.txt
+        gcloud artifacts docker images list-vulnerabilities $(cat /tmp/image-scan.txt) --format='table(vulnerability.effectiveSeverity, vulnerability.cvssScore, noteName, vulnerability.packageIssue[0].affectedPackage, vulnerability.packageIssue[0].affectedVersion.name, vulnerability.packageIssue[0].fixedVersion.name)'
+        gcloud artifacts docker images list-vulnerabilities $(cat /tmp/image-scan.txt) --format='value(vulnerability.effectiveSeverity)' > /tmp/severities.txt
+        echo "Vulnerability Summary:" >> $GITHUB_STEP_SUMMARY
+        echo '```' >> $GITHUB_STEP_SUMMARY
+        cat /tmp/severities.txt | grep -v '^$' | sort | uniq -c >> $GITHUB_STEP_SUMMARY
+        echo '```' >> $GITHUB_STEP_SUMMARY
+        echo >> $GITHUB_STEP_SUMMARY
+        if grep -Exq "$SEVERITY" /tmp/severities.txt; then echo 'Failed vulnerability check' && exit 1; fi
+      env:
+        SEVERITY: low
+    - name: Push Image
+      uses: docker/build-push-action@v3
+      with:
+        context: e2e/actions/deploy-katee
+        file: e2e/actions/deploy-katee/Dockerfile
+        push: true
+        tags: |
+          eu.gcr.io/halfpipe-io/halfpipe-team/someImage:latest
+          eu.gcr.io/halfpipe-io/halfpipe-team/someImage:${{ env.BUILD_VERSION }}
+        build-args: |
+          ARTIFACTORY_PASSWORD=${{ secrets.EE_ARTIFACTORY_PASSWORD }}
+          ARTIFACTORY_URL=${{ secrets.EE_ARTIFACTORY_URL }}
+          ARTIFACTORY_USERNAME=${{ secrets.EE_ARTIFACTORY_USERNAME }}
+          BUILD_VERSION=2.${{ github.run_number }}.0
+          GIT_REVISION=${{ github.sha }}
+          RUNNING_IN_CI=true
+          VAULT_ROLE_ID=${{ secrets.VAULT_ROLE_ID }}
+          VAULT_SECRET_ID=${{ secrets.VAULT_SECRET_ID }}
+    - name: Repository dispatch
+      uses: peter-evans/repository-dispatch@v2
+      with:
+        token: ${{ secrets.EE_REPOSITORY_DISPATCH_TOKEN }}
+        event-type: docker-push:eu.gcr.io/halfpipe-io/halfpipe-team/someImage
+    - name: Summary
+      run: |-
+        echo ":ship: **Image Pushed Successfully**" >> $GITHUB_STEP_SUMMARY
+        echo "" >> $GITHUB_STEP_SUMMARY
+        echo "[eu.gcr.io/halfpipe-io/halfpipe-team/someImage](https://eu.gcr.io/halfpipe-io/halfpipe-team/someImage)" >> $GITHUB_STEP_SUMMARY
+        echo "" >> $GITHUB_STEP_SUMMARY
+        echo "Tags:" >> $GITHUB_STEP_SUMMARY
+        echo "- eu.gcr.io/halfpipe-io/halfpipe-team/someImage:latest" >> $GITHUB_STEP_SUMMARY
+        echo "- eu.gcr.io/halfpipe-io/halfpipe-team/someImage:${{ env.BUILD_VERSION }}" >> $GITHUB_STEP_SUMMARY
+  deploy_to_katee:
+    name: deploy to katee
+    needs:
+    - push_default
+    runs-on: ee-runner
+    timeout-minutes: 60
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
+      with:
+        submodules: recursive
+        ssh-key: ${{ secrets.EE_GITHUB_PRIVATE_KEY }}
+    - name: Get Katee Credentials
+      id: secrets
+      uses: hashicorp/vault-action@v2.4.1
+      with:
+        url: https://vault.halfpipe.io
+        method: approle
+        roleId: ${{ secrets.VAULT_ROLE_ID }}
+        secretId: ${{ secrets.VAULT_SECRET_ID }}
+        exportEnv: true
+        secrets: |
+          /springernature/data/halfpipe-team/katee-halfpipe-team-service-account-prod key | katee-service-account_key ;
+    - name: Deploy to Katee
+      uses: docker://eu.gcr.io/halfpipe-io/ee-katee-vela-cli:latest
+      with:
+        entrypoint: /bin/sh
+        args: -c "cd e2e/actions/deploy-katee; /exe vela up -f $KATEE_APPFILE --publish-version $DOCKER_TAG
+      env:
+        BUILD_VERSION: ${{ env.BUILD_VERSION }}
+        DOCKER_TAG: ${{ env.BUILD_VERSION }}
+        GIT_REVISION: ${{ env.GIT_REVISION }}
+        KATEE_APPFILE: vela.yaml
+        KATEE_APPLICATION_IMAGE: eu.gcr.io/halfpipe-io/halfpipe-team/someImage:${{ env.BUILD_VERSION }}
+        KATEE_APPLICATION_NAME: BLAHBLAH
+        KATEE_GKE_CREDENTIALS: ${{ steps.secrets.outputs.katee-service-account_key }}
+        KATEE_TEAM: halfpipe-team
+    - name: Check Deployment Status
+      uses: docker://eu.gcr.io/halfpipe-io/ee-katee-vela-cli:latest
+      with:
+        entrypoint: /bin/sh
+        args: -c "cd e2e/actions/deploy-katee; /exe deployment-status katee-halfpipe-team BLAHBLAH $PUBLISHED_VERSION
+      env:
+        KATEE_GKE_CREDENTIALS: ${{ steps.secrets.outputs.katee-service-account_key }}
+        KATEE_TEAM: halfpipe-team
+        PUBLISHED_VERSION: ${{ env.BUILD_VERSION }}
