e2e test for nested par/seq

diff --git a/e2e/concourse/parallel/pipelineExpected.yml b/e2e/concourse/parallel/pipelineExpected.yml
--- a/e2e/concourse/parallel/pipelineExpected.yml
+++ b/e2e/concourse/parallel/pipelineExpected.yml
@@ -505,6 +505,158 @@ jobs:
   serial: true
 - build_log_retention:
     minimum_succeeded_builds: 1
+  name: parallel 2 sequence 1 2a
+  plan:
+  - attempts: 2
+    in_parallel:
+      fail_fast: true
+      steps:
+      - get: git
+        params:
+          depth: 1
+        passed:
+        - parallel 2 sequence 1 2
+      - get: version
+        passed:
+        - parallel 2 sequence 1 2
+        trigger: true
+    timeout: 15m
+  - config:
+      caches:
+      - path: ../../../var/halfpipe/cache
+      - path: ../../../halfpipe-cache
+      image_resource:
+        source:
+          registry_mirror:
+            host: eu-mirror.gcr.io
+          repository: alpine
+          tag: latest
+        type: registry-image
+      inputs:
+      - name: git
+      - name: version
+      params:
+        ARTIFACTORY_PASSWORD: ((artifactory.password))
+        ARTIFACTORY_URL: ((artifactory.url))
+        ARTIFACTORY_USERNAME: ((artifactory.username))
+        RUNNING_IN_CI: "true"
+      platform: linux
+      run:
+        args:
+        - -c
+        - |
+          if ! which bash > /dev/null && [ "$SUPPRESS_BASH_WARNING" != "true" ]; then
+            echo "WARNING: Bash is not present in the docker image"
+            echo "If your script depends on bash you will get a strange error message like:"
+            echo "  sh: yourscript.sh: command not found"
+            echo "To fix, make sure your docker image contains bash!"
+            echo "Or if you are sure you don't need bash you can suppress this warning by setting the environment variable \"SUPPRESS_BASH_WARNING\" to \"true\"."
+            echo ""
+            echo ""
+          fi
+
+          if [ -e /etc/alpine-release ]
+          then
+            echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
+            echo "There is a known issue where DNS resolving does not work as expected"
+            echo "https://github.com/gliderlabs/docker-alpine/issues/255"
+            echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
+            echo "we recommend debian:buster-slim as an alternative"
+            echo ""
+            echo ""
+          fi
+
+          export GIT_REVISION=`cat ../../../.git/ref`
+          export BUILD_VERSION=`cat ../../../../version/version`
+
+          ./a
+          EXIT_STATUS=$?
+          if [ $EXIT_STATUS != 0 ] ; then
+            exit 1
+          fi
+        dir: git/e2e/concourse/parallel
+        path: /bin/sh
+    task: parallel-2-sequence-1-2a
+    timeout: 1h
+  serial: true
+- build_log_retention:
+    minimum_succeeded_builds: 1
+  name: parallel 2 sequence 1 2b
+  plan:
+  - attempts: 2
+    in_parallel:
+      fail_fast: true
+      steps:
+      - get: git
+        params:
+          depth: 1
+        passed:
+        - parallel 2 sequence 1 2
+      - get: version
+        passed:
+        - parallel 2 sequence 1 2
+        trigger: true
+    timeout: 15m
+  - config:
+      caches:
+      - path: ../../../var/halfpipe/cache
+      - path: ../../../halfpipe-cache
+      image_resource:
+        source:
+          registry_mirror:
+            host: eu-mirror.gcr.io
+          repository: alpine
+          tag: latest
+        type: registry-image
+      inputs:
+      - name: git
+      - name: version
+      params:
+        ARTIFACTORY_PASSWORD: ((artifactory.password))
+        ARTIFACTORY_URL: ((artifactory.url))
+        ARTIFACTORY_USERNAME: ((artifactory.username))
+        RUNNING_IN_CI: "true"
+      platform: linux
+      run:
+        args:
+        - -c
+        - |
+          if ! which bash > /dev/null && [ "$SUPPRESS_BASH_WARNING" != "true" ]; then
+            echo "WARNING: Bash is not present in the docker image"
+            echo "If your script depends on bash you will get a strange error message like:"
+            echo "  sh: yourscript.sh: command not found"
+            echo "To fix, make sure your docker image contains bash!"
+            echo "Or if you are sure you don't need bash you can suppress this warning by setting the environment variable \"SUPPRESS_BASH_WARNING\" to \"true\"."
+            echo ""
+            echo ""
+          fi
+
+          if [ -e /etc/alpine-release ]
+          then
+            echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
+            echo "There is a known issue where DNS resolving does not work as expected"
+            echo "https://github.com/gliderlabs/docker-alpine/issues/255"
+            echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
+            echo "we recommend debian:buster-slim as an alternative"
+            echo ""
+            echo ""
+          fi
+
+          export GIT_REVISION=`cat ../../../.git/ref`
+          export BUILD_VERSION=`cat ../../../../version/version`
+
+          ./a
+          EXIT_STATUS=$?
+          if [ $EXIT_STATUS != 0 ] ; then
+            exit 1
+          fi
+        dir: git/e2e/concourse/parallel
+        path: /bin/sh
+    task: parallel-2-sequence-1-2b
+    timeout: 1h
+  serial: true
+- build_log_retention:
+    minimum_succeeded_builds: 1
   name: parallel 2 sequence 2 1
   plan:
   - attempts: 2
@@ -827,12 +979,14 @@ jobs:
         params:
           depth: 1
         passed:
-        - parallel 2 sequence 1 2
+        - parallel 2 sequence 1 2a
+        - parallel 2 sequence 1 2b
         - parallel 2 sequence 2 3
         - parallel 2 1
       - get: version
         passed:
-        - parallel 2 sequence 1 2
+        - parallel 2 sequence 1 2a
+        - parallel 2 sequence 1 2b
         - parallel 2 sequence 2 3
         - parallel 2 1
     timeout: 15m
