don't forget to map the pre_promote tasks

diff --git a/e2e/docker-compose-flatten-feature/expected-pipeline.yml b/e2e/docker-compose-flatten-feature/expected-pipeline.yml
--- a/e2e/docker-compose-flatten-feature/expected-pipeline.yml
+++ b/e2e/docker-compose-flatten-feature/expected-pipeline.yml
@@ -8,6 +8,23 @@ resources:
     - e2e/docker-compose
     private_key: ((halfpipe-github.private_key))
     uri: git@github.com:springernature/halfpipe.git
+- name: CF mp-api my-org my-space
+  type: cf-resource
+  source:
+    api: mp-api
+    org: my-org
+    password: ((cloudfoundry.password))
+    space: my-space
+    username: ((cloudfoundry.username))
+  check_every: 24h
+resource_types:
+- name: cf-resource
+  type: registry-image
+  source:
+    password: ((halfpipe-gcr.private_key))
+    repository: eu.gcr.io/halfpipe-io/cf-resource
+    tag: stable
+    username: _json_key
 jobs:
 - name: test
   serial: true
@@ -134,4 +151,109 @@ jobs:
       - path: ../../../halfpipe-cache
     timeout: 1h
     attempts: 1
+- name: deploy-cf
+  serial: true
+  ensure:
+    put: cf halfpipe-cleanup
+    resource: CF mp-api my-org my-space
+    params:
+      command: halfpipe-cleanup
+      manifestPath: git/e2e/docker-compose-flatten-feature/manifest.yml
+      timeout: 1h
+    timeout: 1h
+    attempts: 2
+  plan:
+  - in_parallel:
+      steps:
+      - get: git
+        passed:
+        - two-services
+        trigger: true
+        attempts: 2
+    timeout: 1h
+  - put: cf halfpipe-push
+    resource: CF mp-api my-org my-space
+    params:
+      appPath: git/e2e/docker-compose-flatten-feature
+      command: halfpipe-push
+      gitRefPath: git/.git/ref
+      manifestPath: git/e2e/docker-compose-flatten-feature/manifest.yml
+      testDomain: test.com
+      timeout: 1h
+    timeout: 1h
+    attempts: 2
+  - put: cf halfpipe-check
+    resource: CF mp-api my-org my-space
+    params:
+      command: halfpipe-check
+      manifestPath: git/e2e/docker-compose-flatten-feature/manifest.yml
+      timeout: 1h
+    timeout: 1h
+    attempts: 2
+  - in_parallel:
+      steps:
+      - do:
+        - task: test2
+          config:
+            platform: linux
+            image_resource:
+              type: registry-image
+              source:
+                repository: appropriate/curl
+                tag: latest
+            params:
+              ARTIFACTORY_PASSWORD: ((artifactory.password))
+              ARTIFACTORY_URL: ((artifactory.url))
+              ARTIFACTORY_USERNAME: ((artifactory.username))
+              TEST_ROUTE: halfpipe-example-kotlin-dev-my-space-CANDIDATE.test.com
+            run:
+              path: /bin/sh
+              args:
+              - -c
+              - |
+                which bash > /dev/null
+                if [ $? != 0 ]; then
+                  echo "WARNING: Bash is not present in the docker image"
+                  echo "If your script depends on bash you will get a strange error message like:"
+                  echo "  sh: yourscript.sh: command not found"
+                  echo "To fix, make sure your docker image contains bash!"
+                  echo ""
+                  echo ""
+                fi
+
+                if [ -e /etc/alpine-release ]
+                then
+                  echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
+                  echo "There is a known issue where DNS resolving does not work as expected"
+                  echo "https://github.com/gliderlabs/docker-alpine/issues/255"
+                  echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
+                  echo "we recommend debian:stretch-slim as an alternative"
+                  echo ""
+                  echo ""
+                fi
+
+                export GIT_REVISION=`cat ../../.git/ref`
+
+                \echo hello
+                EXIT_STATUS=$?
+                if [ $EXIT_STATUS != 0 ] ; then
+                  exit 1
+                fi
+              dir: git/e2e/docker-compose-flatten-feature
+            inputs:
+            - name: git
+            caches:
+            - path: ../../../var/halfpipe/cache
+            - path: ../../../halfpipe-cache
+          attempts: 1
+    timeout: 1h
+  - put: cf halfpipe-promote
+    resource: CF mp-api my-org my-space
+    params:
+      command: halfpipe-promote
+      manifestPath: git/e2e/docker-compose-flatten-feature/manifest.yml
+      testDomain: test.com
+      timeout: 1h
+    timeout: 1h
+    attempts: 2
 
