schema and docs improvements

diff --git a/.e2e/artifacts/actions.expected.yml b/.e2e/artifacts/actions.expected.yml
--- a/.e2e/artifacts/actions.expected.yml
+++ b/.e2e/artifacts/actions.expected.yml
@@ -26,8 +26,49 @@ defaults:
     working-directory: .e2e/artifacts
 concurrency: ${{ github.workflow }}
 jobs:
+  update:
+    name: update
+    runs-on: ee-runner
+    timeout-minutes: 60
+    outputs:
+      synced: ${{ steps.sync.outputs.synced }}
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+      with:
+        lfs: true
+        show-progress: false
+        ssh-key: ${{ secrets.EE_GITHUB_PRIVATE_KEY }}
+        submodules: recursive
+    - name: Sync workflow with halfpipe manifest
+      id: sync
+      run: halfpipe-update-workflow
+      env:
+        HALFPIPE_FILE_PATH: .halfpipe.io.yml
+    - name: Commit and push changes to workflow
+      if: steps.sync.outputs.synced == 'false'
+      run: |
+        git config user.name halfpipe-io
+        git config user.email halfpipe-io@springernature.com
+        if git commit -am "[halfpipe] synced workflow $GITHUB_WORKFLOW with halfpipe manifest" && git push; then
+          echo ':white_check_mark: Halfpipe successfully updated the workflow' >> $GITHUB_STEP_SUMMARY
+          echo >> $GITHUB_STEP_SUMMARY
+          echo 'This happened because the workflow was generated from a halfpipe manifest with the `update-pipeline` feature enabled. It keeps the workflow in sync with the halfpipe manifest.' >> $GITHUB_STEP_SUMMARY
+          echo >> $GITHUB_STEP_SUMMARY
+          echo '[Halfpipe Documentation](https://ee.public.springernature.app/rel-eng/halfpipe/features/#update_pipeline)' >> $GITHUB_STEP_SUMMARY
+        else
+          echo ':x: Halfpipe failed to update the workflow' >> $GITHUB_STEP_SUMMARY
+          echo >> $GITHUB_STEP_SUMMARY
+          echo 'This may have happened because newer git commits have already been pushed. Check for newer pipeline runs or manually trigger the workflow.' >> $GITHUB_STEP_SUMMARY
+          echo >> $GITHUB_STEP_SUMMARY
+          echo '[Halfpipe Documentation](https://ee.public.springernature.app/rel-eng/halfpipe/features/#update_pipeline)' >> $GITHUB_STEP_SUMMARY
+          exit 1
+        fi
   create-artifact:
     name: create-artifact
+    needs:
+    - update
+    if: needs.update.outputs.synced == 'true'
     runs-on: ee-runner
     timeout-minutes: 60
     steps:
