Sneaky hack to allow run to deploy to dev katee

diff --git a/.e2e/deploy-katee/concourse.expected.yml b/.e2e/deploy-katee/concourse.expected.yml
--- a/.e2e/deploy-katee/concourse.expected.yml
+++ b/.e2e/deploy-katee/concourse.expected.yml
@@ -422,6 +422,96 @@ jobs:
     task: deploy-to-katee
     timeout: 1h
   serial: true
+- build_log_retention:
+    minimum_succeeded_builds: 1
+  name: deploy to katee dev cluster
+  plan:
+  - attempts: 2
+    in_parallel:
+      fail_fast: true
+      steps:
+      - get: git
+        passed:
+        - deploy to katee different team
+      - get: version
+        passed:
+        - deploy to katee different team
+        trigger: true
+    timeout: 2h
+  - attempts: 2
+    config:
+      caches:
+      - path: ../../../var/halfpipe/cache
+      - path: ../../../halfpipe-cache
+      image_resource:
+        name: ""
+        source:
+          password: ((gcp:platform-gar/token.token))
+          registry_mirror:
+            host: eu-mirror.gcr.io
+          repository: eu.gcr.io/halfpipe-io/ee-run/docker/ee-katee-vela-cli
+          tag: latest
+          username: oauth2accesstoken
+        type: registry-image
+      inputs:
+      - name: git
+      - name: version
+      params:
+        CHECK_INTERVAL: "5"
+        EAID: APPL-437
+        KATE_GKE_PROJECT: dev
+        KATEE_APPFILE: vela.yaml
+        KATEE_GKE_CREDENTIALS: ((gcp:halfpipe-team-katee-dev-namespace-dev/token.token))
+        KATEE_NAMESPACE: katee-dev-namespace
+        MAX_CHECKS: "60"
+        REVISION_FORMAT: version
+        VERY_SECRET: ((another.secret))
+      platform: linux
+      run:
+        args:
+        - -c
+        - |
+          if ! which bash > /dev/null && [ "$SUPPRESS_BASH_WARNING" != "true" ]; then
+            echo "WARNING: Bash is not present in the docker image"
+            echo "If your script depends on bash you will get a strange error message like:"
+            echo "  sh: yourscript.sh: command not found"
+            echo "To fix, make sure your docker image contains bash!"
+            echo "Or if you are sure you don't need bash you can suppress this warning by setting the environment variable \"SUPPRESS_BASH_WARNING\" to \"true\"."
+            echo ""
+            echo ""
+          fi
+
+          if [ -e /etc/alpine-release ]
+          then
+            echo "WARNING: you are running your build in an Alpine based image"
+            echo "There is a known issue where DNS resolving does not work as expected"
+            echo "https://github.com/gliderlabs/docker-alpine/issues/255"
+            echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
+            echo "we recommend debian as an alternative"
+            echo ""
+            echo ""
+          fi
+
+          export GIT_REVISION=`cat ../../.git/ref`
+          export BUILD_VERSION=`cat ../../../version/version`
+
+          \export TAG="${BUILD_VERSION:-$GIT_REVISION}-$(date +%s)"
+          if [ "$REVISION_FORMAT" == "gitref" ]; then
+            export TAG="$GIT_REVISION"
+          elif [ "$REVISION_FORMAT" == "version" ]; then
+            export TAG="$BUILD_VERSION"
+          fi
+
+          halfpipe-deploy
+          EXIT_STATUS=$?
+          if [ $EXIT_STATUS != 0 ] ; then
+            exit 1
+          fi
+        dir: git/.e2e/deploy-katee
+        path: /bin/sh
+    task: deploy-to-katee
+    timeout: 1h
+  serial: true
 resources:
 - check_every: 10m0s
   name: git
